# Transferring Data from Device manufacturer sites to Influxdb
For flexibility and easy of data manipulation, we transfer the data to influx db.
This will also enable us to have the data downloaded and stored in one place - giving us ownership incase our subscription with the device manufacturer expires.

We shall make API calls to the device urls and send the data to the influxdb database. Since different manufacturers have different procedures for API calls, we do upload the data in different batches based on the manufacturer; Quantaq, Clarity, Airgradient

### Prepare tools for the project
First install the packages and modules necessary to implement the steps of the project.

The documentation for the influxdb_client_3 library can be found [here](https://docs.influxdata.com/influxdb3/cloud-dedicated/reference/client-libraries/v3/python/)

In [11]:
#Install operational packages to help in 
#organizing and querrying the data 
import pandas as pd
import numpy as np
import requests 
import json

#Modules to help interact with influxdb
import os, time
from influxdb_client_3 import InfluxDBClient3, Point

#Modules to modify and manipulate time and dates 
from datetime import date, timedelta

Store important athaurization keys to access different databases

In [12]:
#Load the api key and device serial numbers from the envrionment variable 
%reload_ext dotenv
%dotenv
QUANTAQ_APIKEY = os.environ.get("QUANTAQ_APIKEY")
QUANT001_SN = os.environ.get("QUANT001_SN")
QUANT002_SN = os.environ.get("QUANT002_SN")
CLARITY_APIKEY = os.environ.get("CLARITY_APIKEY")
CLARITY_ORGID = os.environ.get("CLARITY_ORGID")

Create a magic function to help in skipping cells so that they run only once. Some cells especially those that involve uplaoding data to the database, can be skipped so that the data is not duplicated when the cells are are run multiple times

In [13]:
from IPython.core.magic import register_cell_magic

@register_cell_magic
def skip(line, cell):
    return

### Set up influxdb
Prepare the database to receive data from the device manufacturer urls

In [41]:
#add this to load and upadte the token file
%reload_ext dotenv
%dotenv

#Define some of the arguments required 
#to write the data to the database

token = os.environ.get("INFLUXDB_TOKEN")
org         =   "Air quality - Harrisburg and Philadelphia"
host        =   "https://us-east-1-1.aws.cloud2.influxdata.com"
database    =   "pilot-harrisburg-home"

client = InfluxDBClient3(host=host, token=token, org=org, database=database)

For automation, Write a function that will later be used to easily upload the data into an influxdb database

In [42]:
def upload_to_inlfuxdb(data_frame_to_save, measurement_name, 
                       index_field, client_name, tag_cols_list):
    """
    A function that takes the name of the measurement(table) 
    and one field name to serve as the index and wites them into
    a defined database on influxdb

    Args:
        data_frame_to_save(df)  : The dataframe to be sent to the database
        measurement_name(string) : The measurement or table name to store the dataset
        index_field(string)     : A timefield from the measurement to be used as an index
                                This also serves as the timeseries reference column
        client_name(object)     : The influxdb object with a defined database 
        tag_cols_list (list)    : A list of column names to act as tags

    Return : 
            Prints that it completed the task
    """ 

    #Make the index field to be the index so that it acts as the timestamp
    data_frame_to_save_index = data_frame_to_save.set_index(index_field)
    
    #Write to the database and the let user know that it is written
    client_name.write(record=data_frame_to_save_index, 
                      data_frame_measurement_name=measurement_name,
                      data_frame_tag_columns=tag_cols_list)
    
    print("Done! Check your influxdb to confirm!")

## 1. Quantaq

The guidelines to make API calls to quantaq can be found [here](https://docs.quant-aq.com/software-apis-and-libraries/quantaq-cloud-api). For using python to manipulate data; find the guidance under the [documentation for the py-quantaq](https://quant-aq.github.io/py-quantaq/usage.html#list-all-final-data-for-a-device); which is a quantaq python library for data manipulation.

### 1.1 Quantaq Setup and Automation

Using the py-QuantAQ library to get data from the web and manipulate it

In [36]:
%%skip
pip install py-quantaq

In [37]:
#Bring in the the quantaq libray and instantiate the client object
from quantaq.utils import to_dataframe
from quantaq import QuantAQAPIClient

client_quantaq = QuantAQAPIClient(api_key=QUANTAQ_APIKEY)

For automation, write a function that gets the data from quantaq website given a time frame. This function can be used to obtain the intial batch of data and subsequently used to update the database

In [38]:
def get_quantaq_data_devices(devices_sn_list, 
                             start_time, 
                             end_time):
    """
    A function that accepts a list of devices and returns the 
    data of different parameters given a start date and end date
    
    Args:
        devices_sn_list(list) : Sns for devices from which to collect data
        start_time: (string)  : Time in the format of 'yyyy-mm-dd'
        end_time: (string)  : Time in the format of 'yyyy-mm-dd'

    Return: 
        quantaq_all_data_df(Dataframe) : Dataframe with the requested data

    """

    #Initialize the dataframe to be used to make a 
    # singular table to save to the influxdb database
    quantaq_all_data_df = []

    #Collect the data all the devices from commissioning date to jan-13-2026
    for device in devices_sn_list:
        for each in pd.date_range(start = start_time, end = end_time):
            quantaq_all_data_df.append(
                to_dataframe(client_quantaq.data.bydate(sn=device, 
                                                        date=str(each.date())))
            )
    quantaq_all_data_df = pd.concat(quantaq_all_data_df)

    #For simplicity remove the model and weather fields 
    columns_to_remove=[]
    for col in quantaq_all_data_df.columns:
        if col[:5]=='model':
            columns_to_remove.append(col) 
        if col[:3]=='met':
            columns_to_remove.append(col) 
    
    #create a new dataframe without the columns
    quant_all_modified = quantaq_all_data_df.copy()

    quant_all_modified.drop(columns_to_remove, 
                            axis=1, 
                            inplace=True)

    return quant_all_modified

The pandas resampling function uses the timestamp as the index in the sampling process, making it difficult to have two or more devices in the same sampling dataframe since several records are likely to have shared timestamps.

Let's write a function that divides the data into separate dataframes according to the device serial numbers, resamples each and combines the dataframes again

In [136]:
def resample_quantaq(df, frequency='1h'):
    """
    The resample_quantaq takes a quantaq dataframe and 
    Returns a dataframe resampled at a given frequency

    Args:
        df (object)        :A dataframe of quantaq data 
                            collected at minute level
        frequency (string) :Frequency of sampling/aggregating
                            see the resample function in pandas
    
    Return:
        df_all_sampled (object) :A dataframe with data resampled 
                             at the stated interval
    """

    #First convert the timestamp to datetime to pervent any errors
    df['timestamp'] = pd.to_datetime(df['timestamp'])

    #Define the dictionary to be used in resampling so that we can 
    # get the mean of numerical fields wiothout losing categorical ones
    cols_dict = {'co': 'mean', 'no':'mean', 
             'no2':'mean', 'o3':'mean', 
             'pm1':'mean', 'pm10':'mean', ''
             'pm25':'mean', 'raw_data_id':'first', 
             'sn':'first',  
             'timestamp_local':'first', 'url':'first', ''
             'geo.lat':'first', 'geo.lon':'first'}
    
    #Define a dataframe to combine all the dataframes for each device
    df_all_sampled = []    

    for device_sn in pd.unique(df.sn):
        #get a dataframe for each device separately
        df_device = df[df['sn']==device_sn]

        #Resample the dataframe of the device 
        df_device_sampled = (df_device.resample('1h',
                                               on='timestamp',).
                                               agg(cols_dict).
                                               reset_index())

        #Add it to the overall dataframe to be returned 
        df_all_sampled.append(df_device_sampled)

    df_all_sampled = pd.concat(df_all_sampled)    

    return df_all_sampled

### 1.2 QuantAQ Minute Data

##### 1.2.1 First Batch of the QuantAQ minute data to influxDB

Get the first batch of the quantaq data from the quantaq website and store the file as pickle so as to avoid length periods of downloading next time. To allow a buffer in the time ranges; It is advisable to have the start date atleast a day before the intended range and the end date atleast a day after (beyond the range).

In [ ]:
%%skip
quantaq_all_data_df = get_quantaq_data_devices(devices_sn_list=['MOD-X-00959','MOD-X-00958'], 
                                               start_time='2025-12-28',
                                               end_time='2026-01-20')

quantaq_all_data_df.to_pickle('quantaq_all_devices_12_2025_to_01_2026')

In [27]:
quant_all_to_01_19_2026 = pd.read_pickle('quantaq_all_devices_12_2025_to_01_2026')

Send the initial quantaq batch to the influxdb database for further querrying and vizualization

In [ ]:
%%skip
#Use the upload function to send this datframe to inlflux
upload_to_inlfuxdb(data_frame_to_save=quant_all_to_01_19_2026, 
                   measurement_name='quantaq-pilot', 
                   index_field='timestamp', 
                   client_name=client,
                   tag_cols_list=['sn','geo.lat','geo.lon'])

##### 1.3 Update the Quantaq minute data to influxdb Database

Get the most recent date from the intended quantaq influxdb measurement (table). This date is to be used as the start date in the update process. Then use two days from now as the end date - to allow a room for error.

In [57]:
query_date = """SELECT *
                FROM  'quantaq-pilot' 
                ORDER BY time DESC LIMIT 1
             """
    
#Use the queery on the influxdb database
table = client.query(query=query_date, language='sql')

#Obtain the date to use as a start date in the uplaoding 
# the most recent data from clarity to influxdb
most_recent_quantaq_df = table.to_pandas()
latest_date_quant = str(most_recent_quantaq_df.time[0])[:10]

#Use two days from now as the end date - for the purposes of buffering
end_date_quant = f'{date.today() + timedelta(days=2)}'

#verify that the date is in the right format and makes sense
print(f'start: {latest_date_quant}')
print(f'start: {end_date_quant}')

start: 2026-02-05
start: 2026-02-07

Use the dates above to get the most recent dataframe from quantaq, then uplaod the data to influxdb.

In [58]:
#%%skip
quantaq_update_df = get_quantaq_data_devices(devices_sn_list=['MOD-X-00959','MOD-X-00958'],
                                             start_time=latest_date_quant,
                                             end_time=end_date_quant)

#Ensure that the data types in a
quantaq_update_df.to_pickle('quantaq_update_df_pickle')

In [59]:
quantaq_update_df_pickle = pd.read_pickle('quantaq_update_df_pickle')

In [60]:
#%%skip
upload_to_inlfuxdb(data_frame_to_save = quantaq_update_df_pickle, 
                   measurement_name='quantaq-pilot', 
                   index_field='timestamp', 
                   client_name=client,
                   tag_cols_list=['sn','geo.lat','geo.lon'])

Done! Check your influxdb to confirm!

### 1.3 QuantAQ Hour Data

##### The First Batch QuantAQ Hour

In [128]:
#%%skip
quantaq_all_data_df_min = get_quantaq_data_devices(devices_sn_list=['MOD-X-00959','MOD-X-00958'], 
                                               start_time='2026-01-08',
                                               end_time='2026-02-01')

quantaq_all_data_df_min.to_pickle('quantaq_all_devices_01_2026_to_02_2026')

In [137]:
quant_all_to_02_01_2026_min = pd.read_pickle('quantaq_all_devices_01_2026_to_02_2026')

Resample the data at 1 hour interval before sending it to influxdb

In [ ]:
quant_all_to_02_01_2026_hr = resample_quantaq(quant_all_to_02_01_2026_min)

Now upload te resampled data to influxdb

In [141]:
#%%skip
#Use the upload function to send this datframe to inlflux
upload_to_inlfuxdb(data_frame_to_save=quant_all_to_02_01_2026_hr, 
                   measurement_name='quantaq-pilot-hour-revised', 
                   index_field='timestamp', 
                   client_name=client,
                   tag_cols_list=['sn','geo.lat','geo.lon'])

Done! Check your influxdb to confirm!

##### 1.3.2 Updating QuantAQ - Hour

In [123]:
query_date = """SELECT *
                FROM  'quantaq-pilot-hour-revised' 
                ORDER BY time DESC LIMIT 1
             """
    
#Use the querry on the influxdb database
table = client.query(query=query_date, language='sql')

#Obtain the date to use as a start date in the uplaoding 
# the most recent data from quantaq to influxdb
most_recent_quantaq_df = table.to_pandas()
latest_date_quant_hr = str(most_recent_quantaq_df.time[0])[:10]

#Use two days from now as the end date - for the purposes of buffering
end_date_quant_hr = f'{date.today() + timedelta(days=2)}'

#verify that the date is in the right format and makes sense
print(f'start: {latest_date_quant_hr}')
print(f'start: {end_date_quant_hr}')

start: 2026-02-01
start: 2026-02-07

In [142]:
quantaq_update_data_df_min = get_quantaq_data_devices(devices_sn_list=['MOD-X-00959','MOD-X-00958'], 
                                               start_time=latest_date_quant_hr,
                                               end_time=end_date_quant_hr)

quantaq_update_data_df_min.to_pickle('quantaq_update_data_df_min')

In [153]:
quantaq_update_df_pickle_hr = pd.read_pickle('quantaq_update_data_df_min')

Resample the updated data at 1 hour frequency and send it to influxdb

In [154]:
quant_update_df_pickle_hr = resample_quantaq(quantaq_update_data_df_min)

In [157]:
quant_update_df_pickle_hr

,timestamp,co,no,no2,o3,pm1,pm10,pm25,raw_data_id,sn,timestamp_local,url,geo.lat,geo.lon
0,2026-02-01 00:00:00,213.603833,-3.124333,12.427500,33.905833,1.076833,3.653667,1.293333,23054182.0,MOD-X-00959,2026-01-31 19:00:51,https://api.quant-aq.com/v1/devices/MOD-X-0095...,40.3156,-76.8962
1,2026-02-01 01:00:00,204.020167,-2.760500,12.091500,34.045667,0.751833,3.448500,1.039500,23058112.0,MOD-X-00959,2026-01-31 20:00:54,https://api.quant-aq.com/v1/devices/MOD-X-0095...,40.3156,-76.8962
2,2026-02-01 02:00:00,206.234576,-3.060339,12.020169,34.086271,0.572373,3.224068,0.811017,23062185.0,MOD-X-00959,2026-01-31 21:00:57,https://api.quant-aq.com/v1/devices/MOD-X-0095...,40.3156,-76.8962
3,2026-02-01 03:00:00,205.334333,-2.834500,12.011833,33.797500,2.784333,5.548167,3.023833,23066184.0,MOD-X-00959,2026-01-31 22:00:00,https://api.quant-aq.com/v1/devices/MOD-X-0095...,40.3156,-76.8962
4,2026-02-01 04:00:00,202.398167,-2.853000,12.031000,34.152833,8.751500,11.054167,8.958667,23070227.0,MOD-X-00959,2026-01-31 23:00:03,https://api.quant-aq.com/v1/devices/MOD-X-0095...,40.3156,-76.8962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,2026-02-05 15:00:00,245.782167,3.357500,15.235000,20.808833,7.990667,13.252833,8.409000,23532009.0,MOD-X-00958,2026-02-05 10:00:01,https://api.quant-aq.com/v1/devices/MOD-X-0095...,40.3156,-76.8961
112,2026-02-05 16:00:00,231.205667,3.166167,9.429000,34.604000,9.541667,12.947500,9.929833,23536879.0,MOD-X-00958,2026-02-05 11:00:03,https://api.quant-aq.com/v1/devices/MOD-X-0095...,40.3156,-76.8961
113,2026-02-05 17:00:00,227.727667,3.079167,10.030667,31.290333,9.840667,13.140333,10.232167,23541734.0,MOD-X-00958,2026-02-05 12:00:06,https://api.quant-aq.com/v1/devices/MOD-X-0095...,40.3156,-76.8961
114,2026-02-05 18:00:00,224.304000,2.744333,6.736333,46.752500,11.151000,15.125000,11.554833,23546232.0,MOD-X-00958,2026-02-05 13:00:08,https://api.quant-aq.com/v1/devices/MOD-X-0095...,40.3156,-76.8961
115,2026-02-05 19:00:00,233.996452,2.248710,5.564516,63.225806,11.017742,20.323226,11.546129,23550600.0,MOD-X-00958,2026-02-05 14:00:10,https://api.quant-aq.com/v1/devices/MOD-X-0095...,40.3156,-76.8961

In [155]:
#Use the upload function to send this datframe to inlflux
upload_to_inlfuxdb(data_frame_to_save=quant_update_df_pickle_hr, 
                   measurement_name='quantaq-pilot-hour-revised', 
                   index_field='timestamp', 
                   client_name=client,
                   tag_cols_list=['sn','geo.lat','geo.lon'])

Done! Check your influxdb to confirm!

## 2. Clarity
The general guidelines for accessing clarity data through the api can be found [here](https://api-guide.clarity.io/); These guideline use examples based on POSTMAN - a webtool for obtaining data using APIs. Clarity has a python library for retrieving data found [here](https://github.com/a2gov/clarityio). Here we use the python library.

### 2.1 Clarity setup and Automation

First install the clarity library

In [14]:
%%skip
pip install clarityio

Make initial connections with the clarity library

In [15]:
import clarityio # Offers methods to connect to the clarity api
from io import StringIO  # Helps to read file as csv and transform to df
api_connection = clarityio.ClarityAPIConnection(api_key=CLARITY_APIKEY, org=CLARITY_ORGID)

Automate the data retrival process from the clarity website

In [21]:
from time import sleep
import requests

def request_and_fetch_a_report(start_time, 
                               end_time, 
                               frequency_clarity='minute', 
                               metric_select='default'):

    """
    A function that retrieves a one-minute-frequency 
    report in csv-wide format for all devices from clarity 
    A maximum of 30 reports can be retrieved in 24 hours

    Args:
        start_time(string) : Starting time for the period of the report 
                             the format of "yyyy-mm-ddThh:mm:ss.sssZ"
        end_time(string)   : End time for the period of the report in 
                             the format of "yyyy-mm-ddThh:mm:ss.sssZ"
        frequency_clarity(string) : The frequency of aggregation due to resampling
                             example: minute(17 mins), hour, day
        metric_select(string)   : The number of metrics to return
                                  "default" or "all". See clarity documentation
                                  for other options

    Return:
        clarity_report_df(DataFrame) : A dataframe report with the clarity 
                                        data in the specified timeframe
    """

    #Define the base part of the clarity url to be used completed in subsequent requests 
    clarity_api_base_url = 'https://clarity-data-api.clarity.io'

    headers = {"x-api-key": CLARITY_APIKEY}

    # request the report
    result = requests.post(url=clarity_api_base_url + "/v2/report-requests",
                           headers=headers,
                           json={
                               "org": CLARITY_ORGID,
                               "report": "datasource-measurements",
                               "allDatasources": True,
                               "outputFrequency": frequency_clarity,
                               "startTime": start_time,
                               "endTime": end_time,
                               "metricSelect": metric_select
                           })
    result.raise_for_status()
    result_json = result.json()
    reportId = result_json['reportId']

    # poll for its completion
    for i in range(12):
        print("sleeping 1 minute")
        sleep(60)
        print("fetching report status ... ", end="")
        statusUrl = clarity_api_base_url + f"/v2/report-requests/{reportId}"
        result = requests.get(url=statusUrl, headers=headers)
        result.raise_for_status()
        result_json = result.json()
        print(result_json.get("reportStatus"))
        if result_json.get("reportStatus") != 'in-progress':
            break

    print(result_json)

    #Define a variable to store the csv file
    filename = None

    if result_json.get("reportStatus") == 'succeeded':
        # if it succeeded, fetch the resulting files
        for i, url in enumerate(result_json['urls']):
            with requests.get(url=url, stream=True) as result:
                result.raise_for_status()
                filename = f"extract_{i}.csv"
                # stream to disk
                with open(f"{filename}", "w") as f:
                    for chunk in result.iter_content(1024 * 1024, decode_unicode=True):
                        f.write(chunk)
    
    #Remove all null columns to reduce redudancy
    report_df = pd.read_csv(filename)    
    clarity_report_df = report_df.dropna(axis='columns', how="all")

    #Remove the 'status' columns and those with unconventianal units 
    strings_to_drop = ['Num','status','DwerAqi',
                       'UkDefraAqi', 'PhDenrAqi']
    pattern_clarity = '|'.join(strings_to_drop)
    cols_to_drop = clarity_report_df.filter(regex=pattern_clarity, 
                                            axis=1).columns.to_list()
    clarity_report_less_cols = clarity_report_df.copy()
    clarity_report_less_cols.drop(columns=cols_to_drop, axis=1, inplace=True)

    return clarity_report_less_cols

### 2.2 Clarity Minute Data

##### 2.2.1 The First Batch of the Clarity Minute data

Use the request_and_fetch_a_report function to get the intial batch report from clarity and then uploadd it to inlfuxdb.

In [ ]:
%%skip

clarity_all_data_df_min = request_and_fetch_a_report(start_time="2025-12-28T00:00:00.000Z",
                                                    end_time="2026-01-20T00:00:00.000Z")


clarity_all_data_df_min.to_pickle('clarity_all_devices_12_2025__to_01_2026')

In [55]:

clarity_all_to_01_19_2026_min = pd.read_pickle('clarity_all_devices_12_2025__to_01_2026')

In [64]:
clarity_all_to_01_19_2026_min

,datasourceId,sourceId,sourceType,outputFrequency,time,locationLatitude,locationLongitude,no2ConcIndividual.raw,o3ConcIndividual.raw,pm10ConcMassIndividual.raw,pm1ConcMassIndividual.raw,pm2_5ConcMassIndividual.raw,pm2_5ConcMassIndividual.value,relHumidInternalIndividual.raw,relHumidInternalIndividual.value,temperatureInternalIndividual.raw,temperatureInternalIndividual.value
0,DYITV0908,A44MFTF3,CLARITY_NODE,minute,2025-12-28T00:07:29.580Z,37.879027,-122.301929,15.50,6.62,95.95,40.30,72.14,28.63,80.55,80.55,0.89,0.89
1,DALCU7773,A93NM49L,CLARITY_NODE,minute,2025-12-28T00:12:12.763Z,37.879027,-122.301929,15.18,2.67,98.40,40.70,74.63,28.39,81.92,81.92,0.97,0.97
2,DYITV0908,A44MFTF3,CLARITY_NODE,minute,2025-12-28T00:25:08.954Z,37.879027,-122.301929,15.36,2.42,109.47,44.84,79.93,32.96,80.78,80.78,0.88,0.88
3,DALCU7773,A93NM49L,CLARITY_NODE,minute,2025-12-28T00:29:43.788Z,37.879027,-122.301929,14.24,3.90,110.05,43.93,82.86,31.82,81.88,81.88,0.92,0.92
4,DYITV0908,A44MFTF3,CLARITY_NODE,minute,2025-12-28T00:42:48.830Z,37.879027,-122.301929,15.89,0.90,110.37,45.23,81.33,32.86,81.37,81.37,0.85,0.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4875,DSCFB3568,A47HWW6V,CLARITY_NODE,minute,2026-01-19T18:28:03.626Z,40.264301,-76.851220,1.34,17.56,14.22,6.08,11.23,9.28,41.61,41.61,4.81,4.81
4876,DALCU7773,A93NM49L,CLARITY_NODE,minute,2026-01-19T18:37:11.380Z,40.315625,-76.895981,6.93,25.18,13.39,6.23,11.31,8.88,45.49,45.49,3.43,3.43
4877,DSCFB3568,A47HWW6V,CLARITY_NODE,minute,2026-01-19T18:45:14.416Z,40.264301,-76.851220,-2.48,15.52,12.38,5.93,10.54,8.86,39.01,39.01,5.07,5.07
4878,DYITV0908,A44MFTF3,CLARITY_NODE,minute,2026-01-19T18:45:36.610Z,40.315627,-76.895969,2.77,20.30,12.54,7.08,11.54,8.60,46.77,46.77,3.44,3.44
4879,DALCU7773,A93NM49L,CLARITY_NODE,minute,2026-01-19T18:54:42.092Z,40.315625,-76.895981,2.55,21.38,12.37,6.00,11.68,8.90,41.89,41.89,3.81,3.81

In [ ]:
%%skip
#Upload the report to influxdb
upload_to_inlfuxdb(data_frame_to_save=clarity_all_data_df_min,
                   measurement_name='clarity-pilot-minute',
                   index_field='time',
                   client_name=client,
                   tag_cols_list=['datasourceId','sourceId','sourceType',
                                  'locationLatitude','locationLongitude']
                   )

##### 2.2.2 Updating the Clarity Minute data

To update the clarity database with the latest; first querry for the latest date in the database and use it as the start date to get data from clarity.

In [145]:
query_date = """SELECT *
                FROM  'clarity-pilot-minute' 
                ORDER BY time DESC LIMIT 1
             """
    
#Use the queery on the influxdb database
table = client.query(query=query_date, language='sql')

#Obtain the date to use as a start date in the uplaoding 
# the most recent data from clarity to influxdb
most_recent_clarity_df = table.to_pandas()
latest_date_clarity = str(most_recent_clarity_df.time[0])[:10] + 'T00:00:00.000Z'

#Use two days from now as the end date - for the purposes of buffering
end_date_clarity = f'{date.today() + timedelta(days=2)}' + 'T00:00:00.000Z'

#verify that the date is in the right format and makes sense
print(f'start: {latest_date_clarity}')
print(f'start: {end_date_clarity}')

start: 2026-02-05T00:00:00.000Z
start: 2026-02-07T00:00:00.000Z

Get an updated dataframe from quantaq to upload in the influxdb database

In [146]:
#%%skip
clarity_update_df = request_and_fetch_a_report(start_time=latest_date_clarity,
                                                    end_time=end_date_clarity)

sleeping 1 minute
fetching report status ... succeeded
{'reportId': 'JBQ6GJ189K', 'reportStatus': 'succeeded', 'message': 'Ready', 'report': 'datasource-measurements', 'urls': ['https://combined-measurements-export-prd.s3.amazonaws.com/historical/JBQ6GJ189K/JBQ6GJ189K.csv.gz?AWSAccessKeyId=ASIAQCFEJKFTTEN6NB7B&Signature=aBlK83IYYzS0msdhZCYL5zMKFPM%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEGwaCXVzLXdlc3QtMiJIMEYCIQDfiXPUXXFF6uGYcYUp77xLLKThdRtfWD%2FcgJjfuSNUeAIhALaD3trjmV8l7vz2WxoOR4u6j82QTaP4c2%2BRxm%2FuD4zQKq8DCDUQBRoMMDA0NjM5NTEwODg3IgxRFEC6fZSySBJVojEqjAM9xdJVJTc7RnznY%2FzOD%2BbPqKCnSUYqIo61wMxEwKr5exPdnj0glqfgInYbNUyMwGlePDX3TxYtRAKMCzDahPzRLNI1ZdjhsyNFbvFmOyMaVaMMFOISub%2FotL4muns8CaufejJGDlywuB2x7fBgyEBQo%2BKyEOFIVn8j7okn3FCdlXQmb3KRPxJFqE%2FydpphA%2FB%2Bw%2BlgZA5wdbVi26GjDbdBWrOFFttv0oLw6OdeAGzq6adGOGMq0Haghzf4O6i2%2FqIduwxHkvJSZ%2FfzAHWp8waWxe%2FS7TAy93uxcT9kecu54niCIGsH%2BCXsUeDRHFs5Sl13Pg6WsxM4uxR%2BV%2F0pUlOVz1%2BpOq2WIUTSap41C%2FTmFl7eZCDFTHHMhGAgNfVZsJUjavmqVPz2OdmAV4txGJNmO3ffrYJ%2Be3Wg4QWStmCNOiSLDiukDLshs1C%2FL7SArFrFP7yE9vDEHQo1dLuoplSK5lildPgqyRHZgzAM%2FZ7miaN5nc%2BAcVjpJwmE97WtvxIG7zCAvwydAb9jDXgwnN2TzAY6nAF1uE%2FjygpG%2FrmafjGigf2LFqmsK6OnMVDYxVyn44XsRsumb9vB1UtV5OpgZbFtb3hKUwWsdaonup35e7O4uKUFdhtVsPVmiR3%2F5mmEydstg0sa%2Fva2MiOe26EGTDMyex8UnXkUcdjs%2BDrKyRWZDpWaNcs7wxjFixbNM8lJb05m6BASGUp2ieVWpd9dimeMfrxuMnVEMx0zVo6ulL4%3D&Expires=1770320881'], 'query': {'datasourceIds': ['DALCU7773', 'DYITV0908', 'DSCFB3568'], 'endTime': '2026-02-07T00:00:00.000Z', 'outputFrequency': 'minute', 'startTime': '2026-02-05T00:00:00.000Z', 'format': 'csv-wide', 'metricLabelStyle': 'canonical', 'metricSelect': 'default'}, 'urlsExpireAt': '2026-02-05T19:48:01.622Z'}

In [147]:
#%%skip
#Upload the report to influxdb
upload_to_inlfuxdb(data_frame_to_save=clarity_update_df,
                   measurement_name='clarity-pilot-minute',
                   index_field='time',
                   client_name=client,
                   tag_cols_list=['datasourceId','sourceId','sourceType',
                                  'locationLatitude','locationLongitude']
                   )

Done! Check your influxdb to confirm!

### 2.3 Clarity Hour Data

##### 2.3.1 First Batch of Clarity

Fetch the data from the clarity website; remember to specify the frequency and select the right metrics

In [22]:
clarity_all_data_df_hour = request_and_fetch_a_report(start_time="2026-01-08T00:00:00.000Z",
                                                    end_time="2026-02-01T00:00:00.000Z",
                                                    frequency_clarity='hour',
                                                    metric_select="all")


clarity_all_data_df_hour.to_pickle('clarity_all_devices_01_2026__to_02_2026')

sleeping 1 minute
fetching report status ... succeeded
{'reportId': 'JB88J4FTQ4', 'reportStatus': 'succeeded', 'message': 'Ready', 'report': 'datasource-measurements', 'urls': ['https://combined-measurements-export-prd.s3.amazonaws.com/historical/JB88J4FTQ4/JB88J4FTQ4.csv.gz?AWSAccessKeyId=ASIAQCFEJKFTYTPRJJ6K&Signature=QjyFpM27gLCzV4T%2B9PVSTtLxA7E%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEGYaCXVzLXdlc3QtMiJHMEUCIEhv%2FW3ZKdPSpu5JXf87AsQhA793t5D3bKsuI%2FefMyVWAiEApz7iEgEuQcyoJFvpA1yOCnA2vihh2mVHcr%2FlvLjBjfkqrwMILxAFGgwwMDQ2Mzk1MTA4ODciDNTgxmQPu%2BbeST1ffiqMAwEhex7aQ1YkNv9CBqZkDMMDWQgZUTdHws1MKcmSSNgVKltVNTMMk6QNPqiZ5Txjp9rlHJnAbrKxGwTUkf9Mkiq7Z%2FtsnLyzYqwHhf5LC1IGxcWy0c%2FoQed4O7gnTkVe5qk%2F%2FSdip8tRs5tewtsX%2Bslze4lfWq57CWPZCh4xQZbZDiJvNQdJjXV4MiJvU%2Bi5k2P5TKfa4DdBae8auxld8ZGctS0Jv%2Bd6JbwajDthIWWcrw%2BpyHR73nw%2BV19IZj1HwKf6jiY1GSk%2FC8SR1eMCOLSAXn4M3aq3zRMbANmA0wNuFdi5vJjkkMOgN%2Fg2TpP94tRlFQyah7dc%2FA8UuCEXmU23M71DbWX2WfCsk%2FXlRg65bkV%2F0ocGqfVKggZZkL9gRjK5LxoW%2Fg9e2ytSkxcNUlFHxUdmKqaeTbcqKRLhHcwLI9pzG1a7aBjjFLyZnHEWM5OGTVTp1SEYoAEe7FDzCAUd4tzV2GbjtQNifG90HFUOzu%2BPa2WHIrEv4fVh%2FKLIJlpB4txkFAQPEQg4eTCQx5LMBjqdASwUrvXQlO0oj%2Bcck9FFySNfRsfLX%2BCYJvK5K%2F9UdtJfXtcn83PBN0VMA%2BTlZ2t2De73jh2avhy8X8%2FWaEzol5ufjU0LXcgo0ZIowTKq0KiMVvb5fIAc5eTYkW87hAVh3ZyfAFrKThYulnzCsV1oH6OIMSoRtbrvS6kZD8oPXYHf19VCZ%2BazzBvbk%2FhJwbS1JMaAwSIAD6qG3gNX0BY%3D&Expires=1770301167'], 'query': {'datasourceIds': ['DALCU7773', 'DYITV0908', 'DSCFB3568'], 'endTime': '2026-02-01T00:00:00.000Z', 'outputFrequency': 'hour', 'startTime': '2026-01-08T00:00:00.000Z', 'format': 'csv-wide', 'metricLabelStyle': 'canonical', 'metricSelect': 'all'}, 'urlsExpireAt': '2026-02-05T14:19:27.848Z'}

In [23]:

clarity_all_to_02_04_2026_hour = pd.read_pickle('clarity_all_devices_01_2026__to_02_2026')

In [43]:
#%%skip
#Upload the report to influxdb
upload_to_inlfuxdb(data_frame_to_save=clarity_all_to_02_04_2026_hour,
                   measurement_name='clarity-pilot-hour',
                   index_field='startOfPeriod',
                   client_name=client,
                   tag_cols_list=['datasourceId','sourceId','sourceType',
                                  'locationLatitude','locationLongitude']
                   )

Done! Check your influxdb to confirm!

##### 2.3.2 Updating Clarity Hour Data to influxdb

In [148]:
query_date = """SELECT *
                FROM  'clarity-pilot-hour' 
                ORDER BY time DESC LIMIT 1
             """
    
#Use the queery on the influxdb database
table = client.query(query=query_date, language='sql')

#Obtain the date to use as a start date in the uplaoding 
# the most recent data from clarity to influxdb
most_recent_clarity_df = table.to_pandas()
latest_date_clarity = str(most_recent_clarity_df.time[0])[:10] + 'T00:00:00.000Z'

#Use two days from now as the end date - for the purposes of buffering
end_date_clarity = f'{date.today() + timedelta(days=2)}' + 'T00:00:00.000Z'

#verify that the date is in the right format and makes sense
print(f'start: {latest_date_clarity}')
print(f'start: {end_date_clarity}')

start: 2026-02-05T00:00:00.000Z
start: 2026-02-07T00:00:00.000Z

In [149]:
clarity_update_df_hour = request_and_fetch_a_report(start_time=latest_date_clarity,
                                                    end_time=end_date_clarity,
                                                    frequency_clarity='hour',
                                                    metric_select='all')

sleeping 1 minute
fetching report status ... succeeded
{'reportId': 'JBHHZPWCNB', 'reportStatus': 'succeeded', 'message': 'Ready', 'report': 'datasource-measurements', 'urls': ['https://combined-measurements-export-prd.s3.amazonaws.com/historical/JBHHZPWCNB/JBHHZPWCNB.csv.gz?AWSAccessKeyId=ASIAQCFEJKFTQG2YVM5W&Signature=oSoMFTFzz8m92mm37OfajfE8g2A%3D&x-amz-security-token=IQoJb3JpZ2luX2VjEGoaCXVzLXdlc3QtMiJHMEUCIAna8iFTUuXC%2BM9b0Jxv69qksRQdgG0tBctduujh75tAAiEA1vsDfw2jx32m7s7yQqeoqwbCUDXZbD1MdSy19AO2F1UqrwMIMxAFGgwwMDQ2Mzk1MTA4ODciDIJJLFCAI707B5YV8CqMA0%2FwFGYK%2BBtTwK2EJBJ6vgCLwgCkEawf6QtY22%2BZE1Xvzu5%2BSBrj8%2BIDFBnbn62MUjTyKlmTA1Fz859MAhZdp6%2B1v%2FzoKw%2BvnquSNTlmhRK8nWK%2FDia0bvyKSrubDFzHACTnPFRrGp%2F2muU3M0G9aRl6Eab8e6%2FAXW%2FsQdGXnNUNUOhXpSRaMNNud0e%2FQnJpuoWNwYX6VRNE56sUXtGOceD7GzzrsVrPPV%2FiP5aHTP1Nor4YCxAUVLoU4cE93w4GzU7Yny9lQXU9mGfO%2FaEKvkfhDuVEEG11M9GsR9%2BcDoOHGHJ3Ey1ukCr1DkG5eR3ljb2XEWzFcreYkgy2BZDE%2Bsdm8BJfrVOv9YkkLvDUxc93UJoKA%2F4up7CFAcpmK1vXLM0STK0J%2B6lCMEjo%2FoMqtJv8sPuIQVx9hO2ofc%2FYfAO%2BT8Gr3VCsim0ETXMoe7jWQMpgXC4il9cpyw05M2s0veFXTy7zpR8vezbCuuivNwmw%2BuOswixbYbTrecAGvScRIApZVAoidFw20%2FVNADDwsZPMBjqdAUHy3wrM51yr7QU620WfIczBT%2FeTyDmIFYejb%2BXTUv9ey3xHYOWS8npCkf8gyqvskVdGTIqZBOUW%2FOjHe9myWKQoYPNMi8HQtZgQPf9S%2BJ6NgyDiG4DiLJ80cvBy9G4lAfkuSlfI3hYFoy1VCrdyamkSfsp3URy5ZIW%2F9%2BIQ6kmxaTcRd3ZGMd8sCOJDs294xsZz7g4NqfXOjszuUp0%3D&Expires=1770320945'], 'query': {'datasourceIds': ['DALCU7773', 'DYITV0908', 'DSCFB3568'], 'endTime': '2026-02-07T00:00:00.000Z', 'outputFrequency': 'hour', 'startTime': '2026-02-05T00:00:00.000Z', 'format': 'csv-wide', 'metricLabelStyle': 'canonical', 'metricSelect': 'all'}, 'urlsExpireAt': '2026-02-05T19:49:05.990Z'}

In [150]:
upload_to_inlfuxdb(data_frame_to_save=clarity_update_df_hour,
                   measurement_name='clarity-pilot-hour',
                   index_field='startOfPeriod',
                   client_name=client,
                   tag_cols_list=['datasourceId','sourceId','sourceType',
                                  'locationLatitude','locationLongitude']
                   )

Done! Check your influxdb to confirm!