## Setting up InfluxDB

The first thing you'll need to do is ensure you have Python 3 installed, this will not work with older versions of Python.
Install the influxdb3-python module. You'll use this to write and query InfluxDB. Run the command below in your terminal:

In [97]:
!pip install influxdb3-python

Requirement already satisfied: influxdb3-python in c:\users\owner\anaconda3\lib\site-packages (0.16.0)
Requirement already satisfied: reactivex>=4.0.4 in c:\users\owner\anaconda3\lib\site-packages (from influxdb3-python) (4.1.0)
Requirement already satisfied: certifi>=14.05.14 in c:\users\owner\anaconda3\lib\site-packages (from influxdb3-python) (2025.7.14)
Requirement already satisfied: python_dateutil>=2.5.3 in c:\users\owner\appdata\roaming\python\python313\site-packages (from influxdb3-python) (2.9.0.post0)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\owner\anaconda3\lib\site-packages (from influxdb3-python) (2.3.0)
Requirement already satisfied: pyarrow>=8.0.0 in c:\users\owner\anaconda3\lib\site-packages (from influxdb3-python) (19.0.0)
Requirement already satisfied: six>=1.5 in c:\users\owner\appdata\roaming\python\python313\site-packages (from python_dateutil>=2.5.3->influxdb3-python) (1.17.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.1.1 in c:\users\owner\anaconda3\lib\site-packages (from reactivex>=4.0.4->influxdb3-python) (4.12.2)

Lastly, let's install pandas which will be helpful for organizing our data output when we query.

In [98]:
import pandas as pd
import numpy as np

Get the permission to access the database

Here, we initialize the token, organization info, and server url host that are needed to set up the initial connection to InfluxDB. The client connection is then established with the InfluxDBClient initialization.

In [99]:
import os, time
from influxdb_client_3 import InfluxDBClient3, Point

#add this to load and upadte the token file
%reload_ext dotenv
%dotenv

token = os.environ.get("INFLUXDB_TOKEN")
org = "Air quality - Harrisburg and Philadelphia"
host = "https://us-east-1-1.aws.cloud2.influxdata.com"

client = InfluxDBClient3(host=host, token=token, org=org)

## Example of a dataset and the querrying process

Uploading the data

In [100]:
database="pilot-harrisburg-home"

data = {
  "point1": {
    "location": "Klamath",
    "species": "bees",
    "count": 23,
  },
  "point2": {
    "location": "Portland",
    "species": "ants",
    "count": 30,
  },
  "point3": {
    "location": "Klamath",
    "species": "bees",
    "count": 28,
  },
  "point4": {
    "location": "Portland",
    "species": "ants",
    "count": 32,
  },
  "point5": {
    "location": "Klamath",
    "species": "bees",
    "count": 29,
  },
  "point6": {
    "location": "Portland",
    "species": "ants",
    "count": 40,
  },
}

for key in data:
  point = (
    Point("census")
    .tag("location", data[key]["location"])
    .field(data[key]["species"], data[key]["count"])
  )
  client.write(database=database, record=point)
  time.sleep(1) # separate points by 1 second

print("Complete. Return to the InfluxDB UI.")

Complete. Return to the InfluxDB UI.

### A sample querry in python

In [101]:
query = """SELECT *
FROM 'census'
WHERE time >= now() - interval '24 hours'
AND ('bees' IS NOT NULL OR 'ants' IS NOT NULL)"""

# Execute the query
table = client.query(query=query, database="pilot-harrisburg-home", language='sql') 

# Convert to dataframe
df = table.to_pandas().sort_values(by="time")
df = pd.DataFrame(df)
df

    ants  bees  location                          time
6    NaN  23.0   Klamath 2025-12-30 18:16:36.910444392
12  30.0   NaN  Portland 2025-12-30 18:16:37.957687959
7    NaN  28.0   Klamath 2025-12-30 18:16:39.004579895
13  32.0   NaN  Portland 2025-12-30 18:16:40.128996893
8    NaN  29.0   Klamath 2025-12-30 18:16:41.213575379
14  40.0   NaN  Portland 2025-12-30 18:16:42.259226257
9    NaN  23.0   Klamath 2025-12-30 19:59:41.347587416
15  30.0   NaN  Portland 2025-12-30 19:59:42.390911325
10   NaN  28.0   Klamath 2025-12-30 19:59:43.432818726
16  32.0   NaN  Portland 2025-12-30 19:59:44.475855861
11   NaN  29.0   Klamath 2025-12-30 19:59:45.524750038
17  40.0   NaN  Portland 2025-12-30 19:59:46.571979980
0    NaN  23.0   Klamath 2025-12-30 23:26:58.869855744
3   30.0   NaN  Portland 2025-12-30 23:26:59.918462096
1    NaN  28.0   Klamath 2025-12-30 23:27:00.972914530
4   32.0   NaN  Portland 2025-12-30 23:27:02.027731473
2    NaN  29.0   Klamath 2025-12-30 23:27:03.081958545
5   40.0   NaN  Portland 2025-12-30 23:27:04.135996761

Aggregate functions take the values of all rows in a table and use them to perform an aggregate operation. The result is output as a new value in a single-row table.

In this example, we use the mean() function to calculate the average value of data points in the last 10 minutes.

In [102]:
query = """SELECT mean(count)
FROM "census"
WHERE time > now() - 10m"""

# Execute the query
table = client.query(query=query, database="pilot-harrisburg-home", language="influxql")

# Convert to dataframe
df = table.to_pandas().sort_values(by="time")
print(df)

KeyError: 'time'

## Connecting Pilot Test Devices to the database

#### The quantaq devices

In [ ]:
#Load the api key from the envrionment variable 
%reload_ext dotenv
%dotenv
QUANTAQ_APIKEY = os.environ.get("QUANTAQ_APIKEY")

First attempt to print the account information as a test

In [ ]:
import requests 
import json

#Define the the account url as defined in the quantaq documentation 
qauntaq_aq_account_url = "https://api.quant-aq.com/v1/account/"

#Use the requests module to obtain the account information
response = requests.get(qauntaq_aq_account_url, auth=(QUANTAQ_APIKEY,""))

#Print the responses for verification
response_json_acc = response.content
response_dict = json.loads(response_json_acc)

#Print the response veritcally 
for info in response_dict.items():
    print(info)

('confirmed', True)
('email', 'izabayoalain@gmail.com')
('first_name', 'Alain')
('id', 3175)
('is_administrator', False)
('last_name', 'Izabayo')
('last_seen', '2025-12-30T18:35:59.856359')
('member_since', '2025-10-22T02:02:36.104424')
('role', 1)
('username', 'Izaalain')

#### Automation 
First create a function that automatates api calls from quantaq

In [ ]:
def get_quantaq_data(url_ending):
    """
    A function that takes a list of words that go immediately after
    after the "https://api.quant-aq.com" of the url and help to 
    get access to scrap data from quantaq

    Args: 
        url_list (list):    A list of strings to be added to the url 
    
    Returns:
        response_json (json): a json string with the requested data        
    """

    #Define the fist part of the url
    url_first_part = "https://api.quant-aq.com/"

    #Initialize a continieoulsy increasing string to be used to complete the url
    url_additional = ""

    #Complete the url with user input strings 
    for adds_on in url_ending:
        url_additional = url_additional+adds_on+"/"        
    complete_url = url_first_part+url_additional

    #Make the call of the response to be returned 
    response_json = requests.get(complete_url, auth=(QUANTAQ_APIKEY,""))

    return response_json.content

In [ ]:
get_quantaq_data(['v1', 'devices', 'MOD-X-00959','data'])

b'{"data":[{"co":199.9,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.43,"no2":6.99,"o3":37.3,"pm1":0.04,"pm10":0.22,"pm25":0.04,"raw_data_id":19965589,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:19:58","timestamp_local":"2025-12-30T18:19:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19965537"},{"co":197.72,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":1.46,"no2":6.44,"o3":37.12,"pm1":0.04,"pm10":8.24,"pm25":0.05,"raw_data_id":19965587,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:18:58","timestamp_local":"2025-12-30T18:18:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19965535"},{"co":203.01,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":0.25,"no2":7.46,"o3":35.64,"pm1":0.04,"pm10":0.25,"pm25":0.07,"raw_data_id":19965588,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:17:58","timestamp_local":"2025-12-30T18:17:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19965536"},{"co":207.59,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":1.18,"no2":7.14,"o3":36.23,"pm1":0.07,"pm10":2.19,"pm25":0.11,"raw_data_id":19965585,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:16:58","timestamp_local":"2025-12-30T18:16:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19965533"},{"co":206.09,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":0.55,"no2":6.54,"o3":36.94,"pm1":0.1,"pm10":0.67,"pm25":0.18,"raw_data_id":19965586,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:15:58","timestamp_local":"2025-12-30T18:15:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19965534"},{"co":236.99,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":0.24,"no2":7.58,"o3":36.13,"pm1":0.13,"pm10":0.49,"pm25":0.22,"raw_data_id":19965246,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:14:58","timestamp_local":"2025-12-30T18:14:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19965194"},{"co":221.47,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":0.86,"no2":7.6,"o3":36.6,"pm1":0.15,"pm10":1.25,"pm25":0.21,"raw_data_id":19965247,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:13:58","timestamp_local":"2025-12-30T18:13:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19965195"},{"co":199.33,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":0.55,"no2":6.6,"o3":36.51,"pm1":0.1,"pm10":0.37,"pm25":0.15,"raw_data_id":19965245,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:12:58","timestamp_local":"2025-12-30T18:12:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19965193"},{"co":193.1,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":1.48,"no2":6.9,"o3":36.83,"pm1":0.28,"pm10":0.3,"pm25":0.3,"raw_data_id":19965249,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:11:58","timestamp_local":"2025-12-30T18:11:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19965197"},{"co":199.87,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.37,"no2":6.52,"o3":36.94,"pm1":0.27,"pm10":1.12,"pm25":0.43,"raw_data_id":19965248,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:10:58","timestamp_local":"2025-12-30T18:10:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19965196"},{"co":199.31,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":0.56,"no2":6.79,"o3":36.34,"pm1":0.12,"pm10":0.49,"pm25":0.22,"raw_data_id":19964908,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:09:58","timestamp_local":"2025-12-30T18:09:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964856"},{"co":193.55,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":0.28,"no2":6.76,"o3":36.82,"pm1":0.23,"pm10":0.88,"pm25":0.31,"raw_data_id":19964909,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:08:58","timestamp_local":"2025-12-30T18:08:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964857"},{"co":202.44,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.02,"no2":7.04,"o3":36.68,"pm1":0.07,"pm10":0.36,"pm25":0.14,"raw_data_id":19964905,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:07:58","timestamp_local":"2025-12-30T18:07:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964853"},{"co":199.37,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":0.28,"no2":6.78,"o3":36.82,"pm1":0.03,"pm10":1.74,"pm25":0.13,"raw_data_id":19964906,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:06:58","timestamp_local":"2025-12-30T18:06:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964854"},{"co":197.39,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":1.5,"no2":6.8,"o3":37.74,"pm1":0.03,"pm10":0.59,"pm25":0.09,"raw_data_id":19964907,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:05:58","timestamp_local":"2025-12-30T18:05:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964855"},{"co":200.87,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.02,"no2":6.43,"o3":36.48,"pm1":0.04,"pm10":0.8,"pm25":0.14,"raw_data_id":19964547,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:04:58","timestamp_local":"2025-12-30T18:04:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964494"},{"co":194.3,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.63,"no2":6.74,"o3":36.81,"pm1":0.13,"pm10":0.47,"pm25":0.25,"raw_data_id":19964546,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:03:58","timestamp_local":"2025-12-30T18:03:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964493"},{"co":193.5,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-1.25,"no2":6.87,"o3":37.76,"pm1":0.17,"pm10":0.46,"pm25":0.24,"raw_data_id":19964544,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:02:58","timestamp_local":"2025-12-30T18:02:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964492"},{"co":200.88,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":0.28,"no2":5.48,"o3":38.38,"pm1":0.06,"pm10":0.28,"pm25":0.15,"raw_data_id":19964543,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:01:58","timestamp_local":"2025-12-30T18:01:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964491"},{"co":196.82,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.01,"no2":6.62,"o3":36.77,"pm1":0.15,"pm10":1.14,"pm25":0.18,"raw_data_id":19964545,"sn":"MOD-X-00959","timestamp":"2025-12-30T23:00:58","timestamp_local":"2025-12-30T18:00:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964495"},{"co":202.49,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.93,"no2":6.92,"o3":36.18,"pm1":0.14,"pm10":0.94,"pm25":0.23,"raw_data_id":19964184,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:59:58","timestamp_local":"2025-12-30T17:59:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964132"},{"co":199.27,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-1.76,"no2":6.02,"o3":37.49,"pm1":0.0,"pm10":0.25,"pm25":0.12,"raw_data_id":19964185,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:58:58","timestamp_local":"2025-12-30T17:58:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964134"},{"co":197.98,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-1.17,"no2":5.86,"o3":38.56,"pm1":0.04,"pm10":0.52,"pm25":0.12,"raw_data_id":19964182,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:57:58","timestamp_local":"2025-12-30T17:57:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964130"},{"co":196.27,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-1.77,"no2":6.39,"o3":37.4,"pm1":0.1,"pm10":0.25,"pm25":0.21,"raw_data_id":19964183,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:56:58","timestamp_local":"2025-12-30T17:56:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964131"},{"co":195.32,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-1.77,"no2":5.68,"o3":38.71,"pm1":0.05,"pm10":0.22,"pm25":0.13,"raw_data_id":19964186,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:55:58","timestamp_local":"2025-12-30T17:55:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19964133"},{"co":198.39,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.28,"no2":6.13,"o3":38.44,"pm1":0.1,"pm10":0.49,"pm25":0.17,"raw_data_id":19963834,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:54:58","timestamp_local":"2025-12-30T17:54:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963781"},{"co":197.29,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.87,"no2":5.52,"o3":38.2,"pm1":0.03,"pm10":0.19,"pm25":0.15,"raw_data_id":19963833,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:53:58","timestamp_local":"2025-12-30T17:53:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963782"},{"co":195.36,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-1.16,"no2":6.23,"o3":37.35,"pm1":0.02,"pm10":0.26,"pm25":0.06,"raw_data_id":19963831,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:52:58","timestamp_local":"2025-12-30T17:52:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963780"},{"co":196.47,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-2.06,"no2":6.62,"o3":37.25,"pm1":0.07,"pm10":0.08,"pm25":0.08,"raw_data_id":19963830,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:51:58","timestamp_local":"2025-12-30T17:51:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963778"},{"co":197.16,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.57,"no2":6.71,"o3":37.28,"pm1":0.13,"pm10":0.91,"pm25":0.27,"raw_data_id":19963832,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:50:58","timestamp_local":"2025-12-30T17:50:58","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963779"},{"co":198.87,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.28,"no2":5.89,"o3":38.12,"pm1":0.05,"pm10":0.3,"pm25":0.1,"raw_data_id":19963499,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:49:57","timestamp_local":"2025-12-30T17:49:57","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963447"},{"co":195.45,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-2.36,"no2":6.69,"o3":37.27,"pm1":0.1,"pm10":4.79,"pm25":0.2,"raw_data_id":19963495,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:48:57","timestamp_local":"2025-12-30T17:48:57","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963443"},{"co":197.16,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-1.17,"no2":6.13,"o3":37.07,"pm1":0.09,"pm10":0.5,"pm25":0.21,"raw_data_id":19963496,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:47:57","timestamp_local":"2025-12-30T17:47:57","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963445"},{"co":199.96,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-2.36,"no2":6.69,"o3":37.27,"pm1":0.06,"pm10":0.14,"pm25":0.1,"raw_data_id":19963498,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:46:57","timestamp_local":"2025-12-30T17:46:57","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963446"},{"co":196.06,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-1.46,"no2":6.04,"o3":37.04,"pm1":0.16,"pm10":1.17,"pm25":0.2,"raw_data_id":19963497,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:45:57","timestamp_local":"2025-12-30T17:45:57","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963444"},{"co":196.52,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-1.97,"no2":5.56,"o3":39.14,"pm1":0.08,"pm10":0.22,"pm25":0.18,"raw_data_id":19963136,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:44:57","timestamp_local":"2025-12-30T17:44:57","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963084"},{"co":191.61,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.81,"no2":5.7,"o3":38.27,"pm1":0.1,"pm10":0.77,"pm25":0.2,"raw_data_id":19963135,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:43:57","timestamp_local":"2025-12-30T17:43:57","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963083"},{"co":198.78,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-1.39,"no2":5.63,"o3":37.79,"pm1":0.25,"pm10":2.45,"pm25":0.29,"raw_data_id":19963137,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:42:57","timestamp_local":"2025-12-30T17:42:57","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963085"},{"co":197.48,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-2.27,"no2":6.11,"o3":37.99,"pm1":0.08,"pm10":2.14,"pm25":0.19,"raw_data_id":19963138,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:41:57","timestamp_local":"2025-12-30T17:41:57","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963086"},{"co":200.55,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":-0.51,"no2":6.04,"o3":37.97,"pm1":0.23,"pm10":3.22,"pm25":0.27,"raw_data_id":19963139,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:40:57","timestamp_local":"2025-12-30T17:40:57","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19963087"},{"co":200.35,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":0.0,"wx_v":0.0,"wx_wd":0.0,"wx_ws":0.0,"wx_ws_scalar":0.0},"model":{"gas":{"co":20508,"no":20509,"no2":20510,"o3":20511},"pm":{"pm1":18867,"pm10":18869,"pm25":18868}},"no":0.66,"no2":6.39,"o3":37.42,"pm1":0.1,"pm10":0.17,"pm25":0.17,"raw_data_id":19962775,"sn":"MOD-X-00959","timestamp":"2025-12-30T22:39:57","timestamp_local":"2025-12-30T17:39:57","url":"https://api.quant-aq.com/v1/devices/MOD-X-00959/data/19962721"},{"co":194.4,"geo":{"lat":40.3156,"lon":-76.8962},"met":{"wx_u":null,"wx_v":0.0,"wx_wd":

In [123]:

binary_data = get_quantaq_data(['v1', 'devices', 'MOD-X-00959', 'data', '?page=1917&per_page=50'])
json_data = binary_data.decode("utf-8") 
dict_data = json.loads(json_data)
dict_data['meta']
df_test = pd.DataFrame(dict_data['data'])
df_test

,co,geo,met,model,no,no2,o3,pm1,pm10,pm25,raw_data_id,sn,timestamp,timestamp_local,url
0,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2781314,MOD-X-00959,2025-06-16T14:42:45,2025-06-16T14:42:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
1,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2781312,MOD-X-00959,2025-06-16T14:41:45,2025-06-16T14:41:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
2,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2781311,MOD-X-00959,2025-06-16T14:40:45,2025-06-16T14:40:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
3,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2781105,MOD-X-00959,2025-06-16T14:39:45,2025-06-16T14:39:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
4,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2781104,MOD-X-00959,2025-06-16T14:38:45,2025-06-16T14:38:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
5,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2781102,MOD-X-00959,2025-06-16T14:37:45,2025-06-16T14:37:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
6,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2781103,MOD-X-00959,2025-06-16T14:36:45,2025-06-16T14:36:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
7,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2781101,MOD-X-00959,2025-06-16T14:35:45,2025-06-16T14:35:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
8,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780889,MOD-X-00959,2025-06-16T14:34:45,2025-06-16T14:34:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
9,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780890,MOD-X-00959,2025-06-16T14:33:45,2025-06-16T14:33:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
10,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780891,MOD-X-00959,2025-06-16T14:32:45,2025-06-16T14:32:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
11,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780892,MOD-X-00959,2025-06-16T14:31:45,2025-06-16T14:31:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
12,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780893,MOD-X-00959,2025-06-16T14:30:45,2025-06-16T14:30:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
13,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780681,MOD-X-00959,2025-06-16T14:29:45,2025-06-16T14:29:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
14,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780678,MOD-X-00959,2025-06-16T14:28:45,2025-06-16T14:28:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
15,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780682,MOD-X-00959,2025-06-16T14:27:45,2025-06-16T14:27:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
16,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780679,MOD-X-00959,2025-06-16T14:26:45,2025-06-16T14:26:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
17,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780680,MOD-X-00959,2025-06-16T14:25:45,2025-06-16T14:25:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
18,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780455,MOD-X-00959,2025-06-16T14:24:45,2025-06-16T14:24:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
19,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780453,MOD-X-00959,2025-06-16T14:23:45,2025-06-16T14:23:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
20,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780451,MOD-X-00959,2025-06-16T14:22:45,2025-06-16T14:22:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
21,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780454,MOD-X-00959,2025-06-16T14:21:45,2025-06-16T14:21:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
22,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780452,MOD-X-00959,2025-06-16T14:20:45,2025-06-16T14:20:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
23,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780239,MOD-X-00959,2025-06-16T14:19:45,2025-06-16T14:19:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
24,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780242,MOD-X-00959,2025-06-16T14:18:45,2025-06-16T14:18:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
25,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780243,MOD-X-00959,2025-06-16T14:17:45,2025-06-16T14:17:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
26,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780241,MOD-X-00959,2025-06-16T14:16:45,2025-06-16T14:16:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
27,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780240,MOD-X-00959,2025-06-16T14:15:45,2025-06-16T14:15:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
28,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780032,MOD-X-00959,2025-06-16T14:14:45,2025-06-16T14:14:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
29,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780029,MOD-X-00959,2025-06-16T14:13:45,2025-06-16T14:13:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
30,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780028,MOD-X-00959,2025-06-16T14:12:45,2025-06-16T14:12:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
31,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780031,MOD-X-00959,2025-06-16T14:11:45,2025-06-16T14:11:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
32,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2780030,MOD-X-00959,2025-06-16T14:10:45,2025-06-16T14:10:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
33,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779821,MOD-X-00959,2025-06-16T14:09:45,2025-06-16T14:09:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
34,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779817,MOD-X-00959,2025-06-16T14:08:45,2025-06-16T14:08:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
35,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779818,MOD-X-00959,2025-06-16T14:07:45,2025-06-16T14:07:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
36,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779819,MOD-X-00959,2025-06-16T14:06:45,2025-06-16T14:06:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
37,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779820,MOD-X-00959,2025-06-16T14:05:45,2025-06-16T14:05:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
38,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779600,MOD-X-00959,2025-06-16T14:04:45,2025-06-16T14:04:45,https://api.quant-aq.com/v1/devices/MOD-X-0095...
39,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779602,MOD-X-00959,2025-06-16T14:03:44,2025-06-16T14:03:44,https://api.quant-aq.com/v1/devices/MOD-X-0095...
40,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779603,MOD-X-00959,2025-06-16T14:02:44,2025-06-16T14:02:44,https://api.quant-aq.com/v1/devices/MOD-X-0095...
41,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779601,MOD-X-00959,2025-06-16T14:01:44,2025-06-16T14:01:44,https://api.quant-aq.com/v1/devices/MOD-X-0095...
42,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779599,MOD-X-00959,2025-06-16T14:00:44,2025-06-16T14:00:44,https://api.quant-aq.com/v1/devices/MOD-X-0095...
43,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779402,MOD-X-00959,2025-06-16T13:59:44,2025-06-16T13:59:44,https://api.quant-aq.com/v1/devices/MOD-X-0095...
44,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779399,MOD-X-00959,2025-06-16T13:58:44,2025-06-16T13:58:44,https://api.quant-aq.com/v1/devices/MOD-X-0095...
45,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779400,MOD-X-00959,2025-06-16T13:57:44,2025-06-16T13:57:44,https://api.quant-aq.com/v1/devices/MOD-X-0095...
46,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779403,MOD-X-00959,2025-06-16T13:56:44,2025-06-16T13:56:44,https://api.quant-aq.com/v1/devices/MOD-X-0095...
47,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779401,MOD-X-00959,2025-06-16T13:55:44,2025-06-16T13:55:44,https://api.quant-aq.com/v1/devices/MOD-X-0095...
48,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779216,MOD-X-00959,2025-06-16T13:54:44,2025-06-16T13:54:44,https://api.quant-aq.com/v1/devices/MOD-X-0095...
49,None,"{'lat': None, 'lon': None}","{'wx_u': 0.0, 'wx_v': 0.0, 'wx_wd': 0.0, 'wx_w...","{'gas': {'co': None, 'no': None, 'no2': None, ...",None,None,None,None,None,None,2779217,MOD-X-00959,2025-06-16T13:53:44,2025-06-16T13:53:44,https://api.quant-aq.com/v1/devices/MOD-X-0095...

In [ ]:
dict_data['meta']

{'first_url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/?page=1&per_page=50',
 'last_url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/?page=1917&per_page=50',
 'next_url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/?page=2&per_page=50',
 'page': 1,
 'pages': 1917,
 'per_page': 50,
 'prev_url': None,
 'total': 95838}