## Transferring Data from Device manufacturer sites to Influxdb
For flexibility and easy of data manipulation, we transfer the data to influx db.
This will also enable us to have the data downloaded and stored in one place - giving us ownership incase our subscription with the device manufacturer expires.

### Prepare tools for the project
First install the packages and modules necessary to implement the steps of the project.

The documentation for the influxdb_client_3 library can be found [here](https://docs.influxdata.com/influxdb3/cloud-dedicated/reference/client-libraries/v3/python/)

In [3]:
#Install operational packages to help in 
#organizing and querrying the data 
import pandas as pd
import numpy as np
import requests 
import json

#Modules to help interact with influxdb
import os, time
from influxdb_client_3 import InfluxDBClient3, Point

Create a magic function to help in skipping cells so that they run only once. Some cells especially those that involve uplaoding data to the database, can be skipped so that the data is not duplicated when the cells are are run multiple times

In [4]:
from IPython.core.magic import register_cell_magic

@register_cell_magic
def skip(line, cell):
    return

### Set up influxdb
Prepare the database to receive data from the device manufacturer urls

In [5]:
#add this to load and upadte the token file
%reload_ext dotenv
%dotenv

#Define some of the arguments required 
#to write the data to the database

token = os.environ.get("INFLUXDB_TOKEN")
org         =   "Air quality - Harrisburg and Philadelphia"
host        =   "https://us-east-1-1.aws.cloud2.influxdata.com"
database    =   "pilot-harrisburg-home"

client = InfluxDBClient3(host=host, token=token, org=org, database=database)

### Upload the data from Devices to influxdb
Make API calls to the device urls and send the data to the influxdb database. Since different manufacturers have different procedures for API calls, we do upload the data in different batches based on the manufacturer

1. QUANTAQ

The guidelines to make API calls to quantaq can be found [here](https://docs.quant-aq.com/software-apis-and-libraries/quantaq-cloud-api). For using python to manipulate data; find the guidance under the [documentation for the py-quantaq](https://quant-aq.github.io/py-quantaq/usage.html#list-all-final-data-for-a-device); which is a quantaq python library for data manipulation.

In [7]:
#Load the api key and device serial numbers from the envrionment variable 
%reload_ext dotenv
%dotenv
QUANTAQ_APIKEY = os.environ.get("QUANTAQ_APIKEY")
QUANT001_SN = os.environ.get("QUANT001_SN")
QUANT002_SN = os.environ.get("QUANT002_SN")
CLARITY_APIKEY = os.environ.get("CLARITY_APIKEY")
CLARITY_ORGID = os.environ.get("CLARITY_ORGID")

In [1]:
def get_quantaq_data(url_ending_list):
    """
    A function that takes a list of words that go immediately after
    after the "https://api.quant-aq.com" of the url and help to 
    get access to scrap data from quantaq

    Args: 
        url_ending_list (list):    A list of strings to be added to the url 
    
    Returns:
        response_dict (dictionary): a dictionary with the requested data        
    """

    #Define the fist part of the url
    url_first_part = "https://api.quant-aq.com"

    #Initialize a continieoulsy increasing string to be used to complete the url
    url_additional = ""

    #Complete the url with user input strings 
    for adds_on in url_ending_list:
        url_additional = url_additional + "/" + adds_on 
    complete_url = url_first_part+url_additional

    #Make the call of the response to be returned 
    response_json = requests.get(complete_url, auth=(QUANTAQ_APIKEY,""))

    #Convert to dictionary for easy manipulation in python
    response_dict = json.loads(response_json.content)

    return response_dict

In [9]:
all_devices = ['MOD-X-00959','MOD-X-00958']
json_data = get_quantaq_data(['v1','data','resampled','MOD-X-00959','2025-11-05','2026-01-11','1h'])
#pd.json_normalize(json_data['data'])
json_data

{'error': 'not found'}

In [10]:

json_data = get_quantaq_data(['v1','devices','MOD-X-00959','data'])

In [ ]:
complete_url = 'https://api.quant-aq.com/v1/data/resampled/MOD-X-00959/2025-11-05/2026-01-11/1h/'

complete_url2 = 'https://api.quant-aq.com/v1/data/most-recent/MOD-X-00959'
complete_url3 = 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/'
response_json = requests.get(complete_url3, auth=(QUANTAQ_APIKEY,""))

#Convert to dictionary for easy manipulation in python
response_data = json.loads(response_json.content)

In [ ]:
complete_url4 = 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data//'
response_json = requests.get(complete_url4, auth=(QUANTAQ_APIKEY,""))
json.loads(response_json.content)

{'error': 'not found'}

In [33]:
response_data

{'data': [{'co': 175.99,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 2.43,
   'no2': 6.67,
   'o3': 38.83,
   'pm1': 8.52,
   'pm10': 11.29,
   'pm25': 8.78,
   'raw_data_id': 23436284,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:43:45',
   'timestamp_local': '2026-02-04T12:43:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23436218'},
  {'co': 181.54,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 2.68,
   'no2': 6.96,
   'o3': 38.73,
   'pm1': 8.74,
   'pm10': 23.45,
   'pm25': 9.0,
   'raw_data_id': 23436287,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:42:45',
   'timestamp_local': '2026-02-04T12:42:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23436219'},
  {'co': 172.8,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.45,
   'no2': 6.93,
   'o3': 37.85,
   'pm1': 8.08,
   'pm10': 10.29,
   'pm25': 8.45,
   'raw_data_id': 23436286,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:41:45',
   'timestamp_local': '2026-02-04T12:41:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23436215'},
  {'co': 177.1,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 4.34,
   'no2': 6.95,
   'o3': 37.82,
   'pm1': 8.12,
   'pm10': 8.46,
   'pm25': 8.3,
   'raw_data_id': 23436285,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:40:45',
   'timestamp_local': '2026-02-04T12:40:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23436217'},
  {'co': 186.06,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.06,
   'no2': 5.96,
   'o3': 38.23,
   'pm1': 8.12,
   'pm10': 10.74,
   'pm25': 8.42,
   'raw_data_id': 23436283,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:39:45',
   'timestamp_local': '2026-02-04T12:39:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23436216'},
  {'co': 185.31,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.06,
   'no2': 6.25,
   'o3': 38.57,
   'pm1': 7.99,
   'pm10': 9.56,
   'pm25': 8.36,
   'raw_data_id': 23435921,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:38:45',
   'timestamp_local': '2026-02-04T12:38:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435853'},
  {'co': 179.09,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 5.36,
   'no2': 7.24,
   'o3': 36.37,
   'pm1': 8.13,
   'pm10': 10.23,
   'pm25': 8.35,
   'raw_data_id': 23435918,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:37:45',
   'timestamp_local': '2026-02-04T12:37:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435850'},
  {'co': 177.99,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 2.94,
   'no2': 7.26,
   'o3': 37.71,
   'pm1': 8.0,
   'pm10': 9.84,
   'pm25': 8.32,
   'raw_data_id': 23435920,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:36:45',
   'timestamp_local': '2026-02-04T12:36:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435852'},
  {'co': 174.08,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.05,
   'no2': 6.28,
   'o3': 37.66,
   'pm1': 7.73,
   'pm10': 17.63,
   'pm25': 7.89,
   'raw_data_id': 23435919,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:35:45',
   'timestamp_local': '2026-02-04T12:35:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435851'},
  {'co': 170.12,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 5.73,
   'no2': 6.9,
   'o3': 36.97,
   'pm1': 8.03,
   'pm10': 9.02,
   'pm25': 8.28,
   'raw_data_id': 23435917,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:34:45',
   'timestamp_local': '2026-02-04T12:34:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435849'},
  {'co': 179.0,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 4.97,
   'no2': 7.91,
   'o3': 36.59,
   'pm1': 8.48,
   'pm10': 9.12,
   'pm25': 8.8,
   'raw_data_id': 23435530,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:33:45',
   'timestamp_local': '2026-02-04T12:33:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435462'},
  {'co': 180.65,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 4.71,
   'no2': 6.17,
   'o3': 37.25,
   'pm1': 7.57,
   'pm10': 21.13,
   'pm25': 7.8,
   'raw_data_id': 23435528,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:32:45',
   'timestamp_local': '2026-02-04T12:32:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435460'},
  {'co': 184.25,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.69,
   'no2': 4.94,
   'o3': 39.14,
   'pm1': 7.31,
   'pm10': 8.32,
   'pm25': 7.47,
   'raw_data_id': 23435527,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:31:45',
   'timestamp_local': '2026-02-04T12:31:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435459'},
  {'co': 173.09,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 2.67,
   'no2': 6.43,
   'o3': 38.93,
   'pm1': 8.35,
   'pm10': 11.6,
   'pm25': 8.6,
   'raw_data_id': 23435529,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:30:45',
   'timestamp_local': '2026-02-04T12:30:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435461'},
  {'co': 177.65,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 2.04,
   'no2': 6.31,
   'o3': 39.45,
   'pm1': 7.9,
   'pm10': 10.95,
   'pm25': 8.21,
   'raw_data_id': 23435526,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:29:45',
   'timestamp_local': '2026-02-04T12:29:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435458'},
  {'co': 177.63,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.05,
   'no2': 5.69,
   'o3': 38.81,
   'pm1': 8.04,
   'pm10': 9.77,
   'pm25': 8.28,
   'raw_data_id': 23435147,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:28:45',
   'timestamp_local': '2026-02-04T12:28:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435080'},
  {'co': 181.28,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 2.81,
   'no2': 5.62,
   'o3': 39.28,
   'pm1': 8.61,
   'pm10': 8.87,
   'pm25': 8.8,
   'raw_data_id': 23435148,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:27:45',
   'timestamp_local': '2026-02-04T12:27:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435079'},
  {'co': 174.97,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.45,
   'no2': 5.74,
   'o3': 38.31,
   'pm1': 8.33,
   'pm10': 9.97,
   'pm25': 8.84,
   'raw_data_id': 23435145,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:26:45',
   'timestamp_local': '2026-02-04T12:26:45',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435077'},
  {'co': 178.13,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 4.98,
   'no2': 6.93,
   'o3': 37.39,
   'pm1': 8.41,
   'pm10': 9.35,
   'pm25': 8.72,
   'raw_data_id': 23435149,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:25:44',
   'timestamp_local': '2026-02-04T12:25:44',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435081'},
  {'co': 170.12,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 4.85,
   'no2': 7.27,
   'o3': 37.7,
   'pm1': 7.97,
   'pm10': 12.82,
   'pm25': 8.43,
   'raw_data_id': 23435146,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:24:44',
   'timestamp_local': '2026-02-04T12:24:44',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23435078'},
  {'co': 173.94,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.83,
   'no2': 6.67,
   'o3': 38.83,
   'pm1': 7.48,
   'pm10': 15.31,
   'pm25': 7.82,
   'raw_data_id': 23434788,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:23:44',
   'timestamp_local': '2026-02-04T12:23:44',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23434720'},
  {'co': 170.18,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 4.73,
   'no2': 7.28,
   'o3': 35.84,
   'pm1': 7.74,
   'pm10': 16.11,
   'pm25': 8.02,
   'raw_data_id': 23434784,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:22:44',
   'timestamp_local': '2026-02-04T12:22:44',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23434716'},
  {'co': 171.41,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.32,
   'no2': 6.37,
   'o3': 38.94,
   'pm1': 7.4,
   'pm10': 9.45,
   'pm25': 7.74,
   'raw_data_id': 23434785,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:21:44',
   'timestamp_local': '2026-02-04T12:21:44',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23434717'},
  {'co': 174.56,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 2.04,
   'no2': 6.34,
   'o3': 38.52,
   'pm1': 8.12,
   'pm10': 10.79,
   'pm25': 8.4,
   'raw_data_id': 23434787,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:20:44',
   'timestamp_local': '2026-02-04T12:20:44',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23434718'},
  {'co': 176.22,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.06,
   'no2': 5.65,
   'o3': 39.27,
   'pm1': 8.15,
   'pm10': 9.49,
   'pm25': 8.5,
   'raw_data_id': 23434786,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:19:44',
   'timestamp_local': '2026-02-04T12:19:44',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23434719'},
  {'co': 178.01,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': 0.0,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 2.55,
   'no2': 5.5,
   'o3': 39.33,
   'pm1': 7.82,
   'pm10': 11.78,
   'pm25': 8.13,
   'raw_data_id': 23434439,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:18:44',
   'timestamp_local': '2026-02-04T12:18:44',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23434371'},
  {'co': 176.36,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.7,
   'no2': 5.32,
   'o3': 38.49,
   'pm1': 8.26,
   'pm10': 9.26,
   'pm25': 8.48,
   'raw_data_id': 23434438,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:17:44',
   'timestamp_local': '2026-02-04T12:17:44',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23434370'},
  {'co': 174.3,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 2.55,
   'no2': 6.32,
   'o3': 38.99,
   'pm1': 8.15,
   'pm10': 11.66,
   'pm25': 8.48,
   'raw_data_id': 23434436,
   'sn': 'MOD-X-00959',
   'timestamp': '2026-02-04T17:16:44',
   'timestamp_local': '2026-02-04T12:16:44',
   'url': 'https://api.quant-aq.com/v1/devices/MOD-X-00959/data/23434369'},
  {'co': 172.12,
   'geo': {'lat': 40.3156, 'lon': -76.8962},
   'met': {'wx_dew_point': 0.0,
    'wx_pressure': 0.0,
    'wx_rh': 0.0,
    'wx_temp': 0.0,
    'wx_u': None,
    'wx_v': 0.0,
    'wx_wd': 0.0,
    'wx_ws': 0.0,
    'wx_ws_scalar': 0.0},
   'model': {'gas': {'co': 20508, 'no': 20509, 'no2': 20510, 'o3': 20511},
    'pm': {'pm1': 18867, 'pm10': 18869, 'pm25': 18868}},
   'no': 3.96,
   'no2': 5.36,
   'o3': 38.02,
   'pm1': 7.49,
   'pm10': 7.72,
   'pm25': 7.72,
   'raw_data_id': 23434435,
   'sn': 'MOD-X-00959',

In [16]:
pd.json_normalize(response_data['data'])

KeyError: 'data'

In [8]:
pd.json_normalize(json_data['data'])

,co,no,no2,o3,pm1,pm10,pm25,raw_data_id,sn,timestamp,...,met.wx_wd,met.wx_ws,met.wx_ws_scalar,model.gas.co,model.gas.no,model.gas.no2,model.gas.o3,model.pm.pm1,model.pm.pm10,model.pm.pm25
0,204.29,0.63,5.69,28.37,4.01,6.79,4.13,21591766,MOD-X-00959,2026-01-16T20:30:44,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
1,210.79,1.31,6.07,29.20,4.14,6.07,4.35,21591765,MOD-X-00959,2026-01-16T20:29:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
2,206.82,1.98,5.43,28.96,3.65,15.23,3.86,21591764,MOD-X-00959,2026-01-16T20:28:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
3,208.46,1.31,5.43,28.96,3.50,3.91,3.70,21591763,MOD-X-00959,2026-01-16T20:27:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
4,209.41,0.80,8.06,26.24,3.99,4.83,4.19,21591762,MOD-X-00959,2026-01-16T20:26:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
5,207.58,0.97,5.79,28.88,4.53,5.05,4.63,21591415,MOD-X-00959,2026-01-16T20:25:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
6,204.78,2.32,5.81,28.43,3.87,4.61,4.01,21591414,MOD-X-00959,2026-01-16T20:24:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
7,212.01,0.62,6.71,28.00,4.77,5.69,4.87,21591416,MOD-X-00959,2026-01-16T20:23:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
8,205.39,1.81,6.06,27.83,4.78,6.15,4.88,21591413,MOD-X-00959,2026-01-16T20:22:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
9,205.64,0.97,5.63,28.80,4.25,4.58,4.34,21591417,MOD-X-00959,2026-01-16T20:21:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
10,207.37,0.63,5.74,28.85,4.25,13.48,4.43,21591091,MOD-X-00959,2026-01-16T20:20:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
11,208.06,0.97,6.11,28.30,4.21,5.36,4.34,21591090,MOD-X-00959,2026-01-16T20:19:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
12,204.58,1.64,5.87,28.91,4.92,7.23,5.05,21591092,MOD-X-00959,2026-01-16T20:18:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
13,205.81,0.63,5.38,30.06,4.07,4.97,4.21,21591089,MOD-X-00959,2026-01-16T20:17:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
14,206.08,2.15,5.57,29.47,4.45,5.01,4.56,21591088,MOD-X-00959,2026-01-16T20:16:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
15,201.90,0.80,6.35,28.14,3.72,4.11,3.86,21590770,MOD-X-00959,2026-01-16T20:15:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
16,207.42,1.16,6.14,28.76,4.32,5.02,4.49,21590766,MOD-X-00959,2026-01-16T20:14:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
17,207.52,1.98,5.63,29.49,4.10,7.06,4.26,21590765,MOD-X-00959,2026-01-16T20:13:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
18,205.53,1.31,6.42,28.63,2.73,3.52,2.82,21590769,MOD-X-00959,2026-01-16T20:12:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
19,205.81,0.97,5.87,28.91,4.53,14.77,4.63,21590767,MOD-X-00959,2026-01-16T20:11:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
20,204.51,0.97,6.46,28.20,4.27,5.03,4.45,21590457,MOD-X-00959,2026-01-16T20:10:43,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
21,203.56,2.15,5.93,29.38,4.24,4.74,4.39,21590456,MOD-X-00959,2026-01-16T20:09:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
22,200.56,0.71,5.77,29.54,3.89,4.71,3.90,21590453,MOD-X-00959,2026-01-16T20:08:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
23,196.80,1.13,5.75,29.53,3.81,4.64,3.92,21590454,MOD-X-00959,2026-01-16T20:07:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
24,203.50,1.30,5.58,31.04,4.06,4.76,4.19,21590455,MOD-X-00959,2026-01-16T20:06:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
25,200.01,0.96,5.73,29.52,3.91,4.70,4.10,21590100,MOD-X-00959,2026-01-16T20:05:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
26,205.21,2.32,6.06,29.88,4.64,5.10,4.88,21590097,MOD-X-00959,2026-01-16T20:04:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
27,200.63,1.64,6.31,29.75,4.35,12.14,4.51,21590101,MOD-X-00959,2026-01-16T20:03:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
28,202.69,1.30,5.74,30.17,4.29,6.62,4.49,21590098,MOD-X-00959,2026-01-16T20:02:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
29,206.78,2.15,5.80,29.54,3.88,7.39,4.00,21590099,MOD-X-00959,2026-01-16T20:01:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
30,205.46,1.81,6.76,28.04,3.65,4.16,3.81,21589776,MOD-X-00959,2026-01-16T20:00:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
31,200.28,0.46,6.52,29.59,4.08,10.70,4.30,21589775,MOD-X-00959,2026-01-16T19:59:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
32,199.33,1.64,6.02,29.87,4.08,15.44,4.27,21589774,MOD-X-00959,2026-01-16T19:58:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
33,203.91,1.30,5.58,30.58,4.05,4.91,4.27,21589773,MOD-X-00959,2026-01-16T19:57:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
34,202.34,1.64,6.06,29.88,3.79,5.54,4.07,21589771,MOD-X-00959,2026-01-16T19:56:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
35,195.37,0.83,5.61,31.04,3.85,4.98,3.97,21589442,MOD-X-00959,2026-01-16T19:55:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
36,197.50,0.70,5.80,31.55,4.06,13.00,4.24,21589443,MOD-X-00959,2026-01-16T19:54:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
37,197.78,1.05,5.74,31.25,3.86,3.97,3.97,21589441,MOD-X-00959,2026-01-16T19:53:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
38,199.89,1.47,5.59,32.12,4.36,6.59,4.47,21589440,MOD-X-00959,2026-01-16T19:52:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
39,199.41,1.47,5.74,30.17,3.94,14.29,4.19,21589444,MOD-X-00959,2026-01-16T19:51:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
40,200.18,1.64,5.40,31.94,4.41,5.40,4.55,21589130,MOD-X-00959,2026-01-16T19:50:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
41,192.52,1.81,5.33,32.08,3.97,17.26,4.21,21589134,MOD-X-00959,2026-01-16T19:49:42,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
42,199.55,1.47,5.80,30.64,3.89,6.26,3.97,21589132,MOD-X-00959,2026-01-16T19:48:41,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
43,199.62,1.64,5.83,31.10,3.94,4.80,4.09,21589133,MOD-X-00959,2026-01-16T19:47:41,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
44,191.35,0.91,5.45,31.80,4.38,12.54,4.59,21589131,MOD-X-00959,2026-01-16T19:46:41,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
45,194.01,2.15,5.53,31.65,4.32,6.21,4.55,21588779,MOD-X-00959,2026-01-16T19:45:41,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
46,196.40,1.13,5.33,30.86,4.48,11.34,4.70,21588778,MOD-X-00959,2026-01-16T19:44:41,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
47,198.02,0.79,5.44,31.79,4.19,6.47,4.42,21588777,MOD-X-00959,2026-01-16T19:43:41,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
48,195.97,1.66,5.44,32.24,3.71,4.73,3.94,21588776,MOD-X-00959,2026-01-16T19:42:41,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868
49,202.88,2.32,5.73,29.52,4.31,6.30,4.52,21588780,MOD-X-00959,2026-01-16T19:41:41,...,0.0,0.0,0.0,20508,20509,20510,20511,18867,18869,18868

Using the py-QuantAQ library to get data from the web and manipulate it

In [9]:
%%skip
pip install py-quantaq

In [10]:
#Bring in the the quantaq libray and instantiate the client object
from quantaq.utils import to_dataframe
from quantaq import QuantAQAPIClient

client_quantaq = QuantAQAPIClient(api_key=QUANTAQ_APIKEY)

Get all the data from the commissioning date to now. 
This command can be performed only once and then the database will be updated regularly thereafter.

In [12]:
%%skip
#Define the devices form which the data will be extracted 
quantaq_devices = ['MOD-X-00959','MOD-X-00958']

#Initialize the dataframe to be used to make a 
# singular table to save to the influxdb database
quantaq_all_data_df = []

#Collect the date all the devices from commissioning date to jan-13-2026
for device in quantaq_devices:
    for each in pd.date_range(start='2025-11-04', end='2026-01-13'):
        quantaq_all_data_df.append(
            to_dataframe(client_quantaq.data.bydate(sn=device, date=str(each.date())))
        )
quantaq_all_data_df = pd.concat(quantaq_all_data_df)

Store the file as pickle so as to avoid length periods of downloading next time

In [12]:
%%skip
quantaq_all_data_df.to_pickle('quantaq_all_devices_2025_11_to_2026_01')

In [13]:
quant_all_to_01_12_2026 = pd.read_pickle('quantaq_all_devices_2025_11_to_2026_01')
quant_all_to_01_12_2026

,co,no,no2,o3,pm1,pm10,pm25,raw_data_id,sn,timestamp,...,met.wx_wd,met.wx_ws,met.wx_ws_scalar,model.gas.co,model.gas.no,model.gas.no2,model.gas.o3,model.pm.pm1,model.pm.pm10,model.pm.pm25
0,38.26,3.48,5.57,7.75,8.67,44.64,9.62,13608141,MOD-X-00959,2025-11-05 23:59:06,...,0.0,0.0,0.0,18903.0,18917.0,18934.0,18935.0,18867,18869,18868
1,29.20,4.00,5.30,8.02,7.98,40.72,8.83,13607850,MOD-X-00959,2025-11-05 23:58:06,...,0.0,0.0,0.0,18903.0,18917.0,18934.0,18935.0,18867,18869,18868
2,30.11,3.45,5.77,8.10,8.60,36.28,9.22,13607849,MOD-X-00959,2025-11-05 23:57:06,...,0.0,0.0,0.0,18903.0,18917.0,18934.0,18935.0,18867,18869,18868
3,27.40,3.99,5.96,7.51,8.31,22.55,9.26,13607848,MOD-X-00959,2025-11-05 23:56:06,...,0.0,0.0,0.0,18903.0,18917.0,18934.0,18935.0,18867,18869,18868
4,32.55,3.27,5.82,8.10,9.02,31.98,9.65,13607845,MOD-X-00959,2025-11-05 23:55:06,...,0.0,0.0,0.0,18903.0,18917.0,18934.0,18935.0,18867,18869,18868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050,231.20,1.00,16.91,36.18,1.54,2.40,1.58,21120552,MOD-X-00958,2026-01-12 00:04:46,...,NaN,NaN,NaN,20450.0,20451.0,18932.0,18933.0,18864,18866,18865
1051,227.44,0.84,17.57,33.76,1.33,2.30,1.40,21120548,MOD-X-00958,2026-01-12 00:03:46,...,NaN,NaN,NaN,20450.0,20451.0,18932.0,18933.0,18864,18866,18865
1052,224.70,-0.02,16.90,34.77,1.08,1.27,1.21,21120549,MOD-X-00958,2026-01-12 00:02:46,...,NaN,NaN,NaN,20450.0,20451.0,18932.0,18933.0,18864,18866,18865
1053,222.11,0.11,16.91,35.71,1.10,2.01,1.17,21120551,MOD-X-00958,2026-01-12 00:01:46,...,NaN,NaN,NaN,20450.0,20451.0,18932.0,18933.0,18864,18866,18865
1054,218.43,1.15,17.59,35.18,1.32,1.37,1.37,21120550,MOD-X-00958,2026-01-12 00:00:46,...,NaN,NaN,NaN,20450.0,20451.0,18932.0,18933.0,18864,18866,18865

In [ ]:
def upload_to_inlfuxdb(data_frame_to_save, measurement_name, 
                       index_field, client_name, tag_cols_list):
    """
    A function that takes the name of the measurement(table) 
    and one field name to serve as the index and wites them into
    a defined database on influxdb

    Args:
        data_frame_to_save(df)  : The dataframe to be sent to the database
        measurement_name(string) : The measurement or table name to store the dataset
        index_field(string)     : A timefield from the measurement to be used as an index
                                This also serves as the timeseries reference column
        client_name(object)     : The influxdb object with a defined database 
        tag_cols_list (list)    : A list of column names to act as tags

    Return : 
            Prints that it completed the task
    """ 

    #Make the index field to be the index so that it acts as the timestamp
    data_frame_to_save_index = data_frame_to_save.set_index(index_field)
    
    #Write to the database and the let user know that it is written
    client_name.write(record=data_frame_to_save_index, 
                      data_frame_measurement_name=measurement_name,
                      data_frame_tag_columns=tag_cols_list)
    
    print("Done! Check your influxdb to confirm!")

Transform the QuantaAQ data obtained through the API into a datframe, and send it to the influxdb database for further querrying and vizualization

In [15]:
#Get the json data to be saved to influxdb from the quantaq
data_meta_quant002_dict = get_quantaq_data(['v1','devices',QUANT002_SN,'data','?per_page=1000'])

#Extract the data part of the transformed data 
# for easy saving to the influxdb database
data_quant002_dict = data_meta_quant002_dict['data']

#Transform the data to a dataframe for 
# easy compatibility with influxdb classes
data_quant002_df = pd.json_normalize(data=data_quant002_dict)

#Use the upload function to send this datframe to inlflux
upload_to_inlfuxdb(data_frame_to_save=data_quant002_df, 
                   measurement_name='quantaq-pilot-tags-clean', 
                   index_field='timestamp', 
                   client_name=client,
                   tag_cols_list=['sn','geo.lat','geo.lon'])

Done! Check your influxdb to confirm!

Save the entrie dataset from commissioning date

#### 2. Clarity
The general guidelines for accessing clarity data through the api can be found [here](https://api-guide.clarity.io/); These guideline use examples based on POSTMAN - a webtool for obtaining data using APIs. Clarity has a python library for retrieving data found [here](https://github.com/a2gov/clarityio). Here we use the python library.

First install the clarity library

In [16]:
%%skip
pip install clarityio

Make initial connections with the clarity library

In [17]:
import clarityio # Offers methods to connect to the clarity api
from io import StringIO  # Helps to read file as csv and transform to df
api_connection = clarityio.ClarityAPIConnection(api_key=CLARITY_APIKEY, org=CLARITY_ORGID)

Getting the data from the APi before uploading to the database

In [18]:
def create_df_from_date(start_time):

    """
    A function that produces a clarity dataframe from a given to now

    Args:
        start_time(string) : Date and time from to start pulling records
                             In the format of '2026-01-04T00:00:00Z' 
    
    Return:
        latest_clarity_df (dataframe) : A dataframe with data from the given date to now

    """

    #Attemopt to get data from a certain date
    request_body_pilot = {
        'allDatasources': True,
        'outputFrequency': 'hour',
        'format':       'csv-wide',
        'startTime': start_time
        }

    #get the data in form of csv, ocnvert it to a dataframe and 
    # for easy manipulation and saving to the database
    response_wide2 = api_connection.get_recent_measurements(data=request_body_pilot)
    clarity_df = pd.read_csv(StringIO(response_wide2), sep=",")

    #Ensure that only meaningful columns exist to allow 
    # easy data search and manipulation in influxdb
    latest_clarity_df = clarity_df.dropna(axis='columns', how='all')

    return latest_clarity_df

Upload the data from commissioning date to now. This will be the basis from which to contineously update the data

In [ ]:

commissioning_time = '2026-01-04T01:00:00Z'
commission_to_jan_26_df= create_df_from_date(start_time=commissioning_time)

In [20]:
commission_to_jan_26_df

,datasourceId,sourceId,sourceType,outputFrequency,startOfPeriod,endOfPeriod,locationLatitude,locationLongitude,no2Conc1HourMean.raw,no2Conc1HourMean.status,...,pm2_5ConcNum1HourMean.value,pm2_5ConcNum24HourRollingMean.raw,pm2_5ConcNum24HourRollingMean.status,pm2_5ConcNum24HourRollingMean.value,relHumidInternal1HourMean.raw,relHumidInternal1HourMean.status,relHumidInternal1HourMean.value,temperatureInternal1HourMean.raw,temperatureInternal1HourMean.status,temperatureInternal1HourMean.value
0,DYITV0908,A44MFTF3,CLARITY_NODE,hour,2026-01-13T15:00:00Z,2026-01-13T16:00:00Z,40.315627,-76.895969,5.14,calibration-missing,...,15.31,20.34,sensor-ready,20.34,55.47,sensor-ready,55.47,4.56,sensor-ready,4.56
1,DSCFB3568,A47HWW6V,CLARITY_NODE,hour,2026-01-13T15:00:00Z,2026-01-13T16:00:00Z,40.264301,-76.851220,1.04,calibration-missing,...,10.21,12.04,sensor-ready,12.04,44.97,sensor-ready,44.97,6.87,sensor-ready,6.87
2,DALCU7773,A93NM49L,CLARITY_NODE,hour,2026-01-13T15:00:00Z,2026-01-13T16:00:00Z,40.315625,-76.895981,16.42,calibration-missing,...,15.34,19.37,sensor-ready,19.37,54.39,sensor-ready,54.39,4.50,sensor-ready,4.50
3,DYITV0908,A44MFTF3,CLARITY_NODE,hour,2026-01-13T14:00:00Z,2026-01-13T15:00:00Z,40.315627,-76.895969,28.39,calibration-missing,...,23.07,20.19,sensor-ready,20.19,68.29,sensor-ready,68.29,-0.05,sensor-ready,-0.05
4,DSCFB3568,A47HWW6V,CLARITY_NODE,hour,2026-01-13T14:00:00Z,2026-01-13T15:00:00Z,40.264301,-76.851220,8.90,calibration-missing,...,11.78,12.07,sensor-ready,12.07,55.43,sensor-ready,55.43,2.09,sensor-ready,2.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,DSCFB3568,A47HWW6V,CLARITY_NODE,hour,2026-01-10T16:00:00Z,2026-01-10T17:00:00Z,40.264301,-76.851220,13.16,calibration-missing,...,13.01,27.92,sensor-ready,27.92,74.44,sensor-ready,74.44,6.21,sensor-ready,6.21
215,DALCU7773,A93NM49L,CLARITY_NODE,hour,2026-01-10T16:00:00Z,2026-01-10T17:00:00Z,40.315625,-76.895981,13.60,calibration-missing,...,13.33,34.38,sensor-ready,34.38,73.82,sensor-ready,73.82,6.82,sensor-ready,6.82
216,DYITV0908,A44MFTF3,CLARITY_NODE,hour,2026-01-10T15:00:00Z,2026-01-10T16:00:00Z,40.315627,-76.895969,10.66,calibration-missing,...,11.92,38.95,sensor-ready,38.95,74.66,sensor-ready,74.66,6.35,sensor-ready,6.35
217,DSCFB3568,A47HWW6V,CLARITY_NODE,hour,2026-01-10T15:00:00Z,2026-01-10T16:00:00Z,40.264301,-76.851220,11.03,calibration-missing,...,12.77,28.64,sensor-ready,28.64,73.80,sensor-ready,73.80,6.36,sensor-ready,6.36
218,DALCU7773,A93NM49L,CLARITY_NODE,hour,2026-01-10T15:00:00Z,2026-01-10T16:00:00Z,40.315625,-76.895981,10.40,calibration-missing,...,10.63,35.52,sensor-ready,35.52,72.58,sensor-ready,72.58,6.80,sensor-ready,6.80

In [21]:
commission_to_jan_26_df[['sourceId','startOfPeriod','endOfPeriod']].sort_values(by='startOfPeriod', ascending=True)

     sourceId         startOfPeriod           endOfPeriod
218  A93NM49L  2026-01-10T15:00:00Z  2026-01-10T16:00:00Z
217  A47HWW6V  2026-01-10T15:00:00Z  2026-01-10T16:00:00Z
216  A44MFTF3  2026-01-10T15:00:00Z  2026-01-10T16:00:00Z
213  A44MFTF3  2026-01-10T16:00:00Z  2026-01-10T17:00:00Z
215  A93NM49L  2026-01-10T16:00:00Z  2026-01-10T17:00:00Z
..        ...                   ...                   ...
4    A47HWW6V  2026-01-13T14:00:00Z  2026-01-13T15:00:00Z
3    A44MFTF3  2026-01-13T14:00:00Z  2026-01-13T15:00:00Z
2    A93NM49L  2026-01-13T15:00:00Z  2026-01-13T16:00:00Z
1    A47HWW6V  2026-01-13T15:00:00Z  2026-01-13T16:00:00Z
0    A44MFTF3  2026-01-13T15:00:00Z  2026-01-13T16:00:00Z

[219 rows x 3 columns]

Use the influxdb query package to get the latest date from the database. Look at the date and ensure that it makes sense.

In [22]:
query_date = """SELECT *
                FROM  'clarity-pilot-tags' 
                ORDER BY time DESC LIMIT 1
             """
    
#Use the queery on the influxdb database
table = client.query(query=query_date, language='sql')

#Obtain the date to use as a start date in the uplaoding 
# the most recent data from clarity to influxdb
most_recent_clarity_df = table.to_pandas()
latest_date = most_recent_clarity_df.startOfPeriod[0]

#verify that the date is in the right format and makes sense
print(latest_date)

2026-01-09T20:00:00Z

From the clarity API, get the data from the most recent date of saving in influxdb to now. And then make a dataframe from it which will later be added to the influxdb database

In [23]:
latest_clarity_df = create_df_from_date(start_time=latest_date)

In [24]:
#Sample for this week (01/04/25 - 01/09/25)
week_df = create_df_from_date(start_time="2026-01-04T00:00:00Z")

Upload this dataframe to the influxdb database in the cloud. Ensure that the measurement name and client name in the uplaod function match with what was used to generate the dataframe

In [25]:
#Define the columns to use as tags so that datapoints 
# recorded at exactly the same time can be recorded
columns_tags = ['datasourceId', 'locationLatitude',
                'locationLongitude','sourceId']
#Use the upload function to send this datframe to inlflux
upload_to_inlfuxdb(data_frame_to_save=week_df, 
                   measurement_name='clarity-pilot-tags', 
                   index_field='endOfPeriod', 
                   client_name=client,
                   tag_cols_list=columns_tags)

Done! Check your influxdb to confirm!

Since the create_df_from_date function can only get data for a short time (24 hours for minute frequencies). We can instead retrieve large chucks of data using reports and then use the create_df_from_date for small amaounts of data

In [ ]:
from time import sleep
import requests

def request_and_fetch_a_report(start_time, end_time):

    """
    A function that retrieves a one-minute-frequency 
    report in csv-wide format for all devices from clarity 
    A maximum of 30 reports can be retrieved in 24 hours

    Args:
        start_time(string) : Starting time for the period of the report 
                             the format of "yyyy-mm-ddThh:mm:ss.sssZ"
        end_time(string)   : End time for the period of the report in 
                             the format of "yyyy-mm-ddThh:mm:ss.sssZ"

    Return:
        clarity_report_df(DataFrame) : A dataframe report with the clarity 
                                        data in the specified timeframe
    """

    #Define the base part of the clarity url to be used completed in subsequent requests 
    clarity_api_base_url = 'https://clarity-data-api.clarity.io'

    headers = {"x-api-key": CLARITY_APIKEY}

    # request the report
    result = requests.post(url=clarity_api_base_url + "/v2/report-requests",
                           headers=headers,
                           json={
                               "org": CLARITY_ORGID,
                               "report": "datasource-measurements",
                               "allDatasources": True,
                               "outputFrequency": "minute",
                               "startTime": start_time,
                               "endTime": end_time,
                           })
    result.raise_for_status()
    result_json = result.json()
    reportId = result_json['reportId']

    # poll for its completion
    for i in range(12):
        print("sleeping 1 minute")
        sleep(60)
        print("fetching report status ... ", end="")
        statusUrl = clarity_api_base_url + f"/v2/report-requests/{reportId}"
        result = requests.get(url=statusUrl, headers=headers)
        result.raise_for_status()
        result_json = result.json()
        print(result_json.get("reportStatus"))
        if result_json.get("reportStatus") != 'in-progress':
            break

    print(result_json)

    #Define a variable to store the csv file
    filename = None

    if result_json.get("reportStatus") == 'succeeded':
        # if it succeeded, fetch the resulting files
        for i, url in enumerate(result_json['urls']):
            with requests.get(url=url, stream=True) as result:
                result.raise_for_status()
                filename = f"extract_{i}.csv"
                # stream to disk
                with open(f"{filename}", "w") as f:
                    for chunk in result.iter_content(1024 * 1024, decode_unicode=True):
                        f.write(chunk)
    
    #Remove all null columns to reduce redudancy
    report_df = pd.read_csv(filename)
    
    clarity_report_df = report_df.dropna(axis='columns', how="all")


    return clarity_report_df

Use the request_and_fetch_a_report function to get the report from clarity and then uplaod it to inlfuxdb.

In [ ]:
clarity_from_comm_df = request_and_fetch_a_report(start_time="2025-11-01T00:00:00.000Z",
                                                    end_time="2026-01-15T00:00:00.000Z")

In [68]:
#Upload the report to influxdb
upload_to_inlfuxdb(data_frame_to_save=clarity_from_comm_df,
                   measurement_name='clarity-pilot-alldata-tags',
                   index_field='time',
                   client_name=client,
                   tag_cols_list=['datasourceId','sourceId','sourceType',
                                  'locationLatitude','locationLongitude']
                   )
clarity_from_comm_df

ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 13 Jan 2026 20:57:08 GMT', 'Content-Type': 'application/json', 'Content-Length': '18189', 'Connection': 'keep-alive', 'influxdata-partial-write': 'true', 'trace-id': '5ae253a60f22879a', 'trace-sampled': 'false', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Influxdb-Request-ID': '753466882426ce9e429bc9d307d5a527', 'X-Influxdb-Build': 'Cloud'})
HTTP response body: {"code":"invalid","message":"partial write has occurred, errors encountered on line(s): line 1: observed timestamp 2025-11-07T18:08:37.537+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 2: observed timestamp 2025-11-07T18:13:00.180+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 3: observed timestamp 2025-11-07T18:25:52.700+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 4: observed timestamp 2025-11-07T18:30:27.845+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 5: observed timestamp 2025-11-07T18:43:07.319+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 6: observed timestamp 2025-11-07T18:47:55.433+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 7: observed timestamp 2025-11-07T19:00:22.010+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 8: observed timestamp 2025-11-07T19:05:21.967+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 9: observed timestamp 2025-11-07T19:17:39.603+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 10: observed timestamp 2025-11-07T19:22:49.699+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 11: observed timestamp 2025-11-07T19:34:54.027+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 12: observed timestamp 2025-11-07T19:40:17.446+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 13: observed timestamp 2025-11-07T19:52:08.612+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 14: observed timestamp 2025-11-07T19:57:44.954+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 15: observed timestamp 2025-11-07T20:09:22.910+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 16: observed timestamp 2025-11-07T20:15:12.665+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 17: observed timestamp 2025-11-07T20:26:37.361+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 18: observed timestamp 2025-11-07T20:32:41.011+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 19: observed timestamp 2025-11-07T20:43:55.013+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 20: observed timestamp 2025-11-07T20:50:08.830+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 21: observed timestamp 2025-11-07T21:07:36.737+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 22: observed timestamp 2025-11-07T21:13:36.792+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 23: observed timestamp 2025-11-07T21:25:04.468+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 24: observed timestamp 2025-11-07T21:30:55.303+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 25: observed timestamp 2025-11-07T21:42:32.095+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 26: observed timestamp 2025-11-07T21:48:11.134+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 27: observed timestamp 2025-11-07T21:59:59.729+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 28: observed timestamp 2025-11-07T22:05:30.302+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 29: observed timestamp 2025-11-07T22:17:27.553+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 30: observed timestamp 2025-11-07T22:22:49.208+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 31: observed timestamp 2025-11-07T22:34:58.201+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 32: observed timestamp 2025-11-07T22:40:05.585+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 33: observed timestamp 2025-11-07T22:52:25.746+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 34: observed timestamp 2025-11-07T22:57:21.857+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 35: observed timestamp 2025-11-07T23:09:53.199+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 36: observed timestamp 2025-11-07T23:14:38.188+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 37: observed timestamp 2025-11-07T23:27:21.067+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 38: observed timestamp 2025-11-07T23:31:57.582+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 39: observed timestamp 2025-11-07T23:44:48.764+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 40: observed timestamp 2025-11-07T23:49:16.733+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 41: observed timestamp 2025-11-08T00:02:16.590+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 42: observed timestamp 2025-11-08T00:06:32.796+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 43: observed timestamp 2025-11-08T00:19:44.432+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 44: observed timestamp 2025-11-08T00:23:52.226+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 45: observed timestamp 2025-11-08T00:37:12.227+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 46: observed timestamp 2025-11-08T00:41:11.442+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 47: observed timestamp 2025-11-08T00:54:43.201+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 48: observed timestamp 2025-11-08T00:58:27.750+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 49: observed timestamp 2025-11-08T01:12:10.998+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 50: observed timestamp 2025-11-08T01:15:44.490+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 51: observed timestamp 2025-11-08T01:29:38.611+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 52: observed timestamp 2025-11-08T01:33:01.369+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 53: observed timestamp 2025-11-08T01:47:06.160+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 54: observed timestamp 2025-11-08T01:50:18.696+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 55: observed timestamp 2025-11-08T02:04:33.916+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 56: observed timestamp 2025-11-08T02:07:38.895+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 57: observed timestamp 2025-11-08T02:22:01.810+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 58: observed timestamp 2025-11-08T02:32:10.296+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 59: observed timestamp 2025-11-08T02:39:29.671+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 60: observed timestamp 2025-11-08T02:49:27.743+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 61: observed timestamp 2025-11-08T02:56:57.439+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 62: observed timestamp 2025-11-08T03:06:45.193+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 63: observed timestamp 2025-11-08T03:14:25.431+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 64: observed timestamp 2025-11-08T03:24:02.528+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 65: observed timestamp 2025-11-08T03:31:53.188+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 66: observed timestamp 2025-11-08T03:41:19.999+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 67: observed timestamp 2025-11-08T03:49:20.908+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 68: observed timestamp 2025-11-08T03:58:37.613+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 69: observed timestamp 2025-11-08T04:06:48.455+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 70: observed timestamp 2025-11-08T04:15:54.869+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 71: observed timestamp 2025-11-08T04:24:16.243+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 72: observed timestamp 2025-11-08T04:33:12.332+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 73: observed timestamp 2025-11-08T04:41:43.503+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 74: observed timestamp 2025-11-08T04:50:32.482+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 75: observed timestamp 2025-11-08T04:59:10.851+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 76: observed timestamp 2025-11-08T05:07:52.330+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 77: observed timestamp 2025-11-08T05:16:38.148+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 78: observed timestamp 2025-11-08T05:25:09.199+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 79: observed timestamp 2025-11-08T05:34:05.527+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 80: observed timestamp 2025-11-08T05:42:26.174+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 81: observed timestamp 2025-11-08T05:51:32.847+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 82: observed timestamp 2025-11-08T05:59:43.026+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 83: observed timestamp 2025-11-08T06:09:00.328+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 84: observed timestamp 2025-11-08T06:16:59.650+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 85: observed timestamp 2025-11-08T06:26:28.027+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 86: observed timestamp 2025-11-08T06:34:16.582+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 87: observed timestamp 2025-11-08T06:43:55.564+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 88: observed timestamp 2025-11-08T06:51:33.412+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 89: observed timestamp 2025-11-08T07:01:23.150+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 90: observed timestamp 2025-11-08T07:08:53.255+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 91: observed timestamp 2025-11-08T07:18:50.736+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 92: observed timestamp 2025-11-08T07:26:12.994+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 93: observed timestamp 2025-11-08T07:36:18.250+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 94: observed timestamp 2025-11-08T07:43:29.978+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 95: observed timestamp 2025-11-08T07:53:45.874+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 96: observed timestamp 2025-11-08T08:00:46.970+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 97: observed timestamp 2025-11-08T08:11:13.717+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 98: observed timestamp 2025-11-08T08:18:04.284+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 99: observed timestamp 2025-11-08T08:28:41.788+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00\nline 100: observed timestamp 2025-11-08T08:35:21.403+00:00 is outside of the retention period for the namespace: minimum acceptable timestamp is 2025-12-14T20:57:07.853076198+00:00","line":1}

In [67]:
clarity_from_comm_df.columns

Index(['datasourceId', 'sourceId', 'sourceType', 'outputFrequency', 'time',
       'locationLatitude', 'locationLongitude', 'no2ConcIndividual.raw',
       'no2ConcIndividual.status', 'no2ConcIndividual.value',
       'o3ConcIndividual.raw', 'o3ConcIndividual.status',
       'pm10ConcMassIndividual.raw', 'pm10ConcMassIndividual.status',
       'pm10ConcNumIndividual.raw', 'pm10ConcNumIndividual.status',
       'pm10ConcNumIndividual.value', 'pm1ConcMassIndividual.raw',
       'pm1ConcMassIndividual.status', 'pm1ConcNumIndividual.raw',
       'pm1ConcNumIndividual.status', 'pm1ConcNumIndividual.value',
       'pm2_5ConcMassIndividual.raw', 'pm2_5ConcMassIndividual.status',
       'pm2_5ConcMassIndividual.value', 'pm2_5ConcNumIndividual.raw',
       'pm2_5ConcNumIndividual.status', 'pm2_5ConcNumIndividual.value',
       'relHumidInternalIndividual.raw', 'relHumidInternalIndividual.status',
       'relHumidInternalIndividual.value', 'temperatureInternalIndividual.raw',
       'temperatureInternalIndividual.status',
       'temperatureInternalIndividual.value'],
      dtype='object')

#### 2. AirGradient

In [ ]:
query_date = """SELECT *
                FROM  'airgradient-pilot-hour' 
                ORDER BY time DESC LIMIT 1
             """
    
#Use the queery on the influxdb database
table = client.query(query=query_date, language='sql')

#Obtain the date to use as a start date in the uplaoding 
# the most recent data from airgradient to influxdb
most_recent_airgradient_df = table.to_pandas()
latest_date_airgradient_hr = str(most_recent_airgradient_df.
                              time[0])[:10].replace('-','')

#Use two days from now as the end date - for the purposes of buffering
end_date_airgradient_hr = f'{date.today() + timedelta(days=2)}'[:10].replace('-','')

#verify that the date is in the right format and makes sense
print(f'start: {latest_date_airgradient_hr }')
print(f'end: {end_date_airgradient_hr}')